### DISCUSSION TITLE
FIPS Problem

### DISCUSSION THREAD

**Discussion by sdurig1** [freeipa/ansible-freeipa#1127] [Q&A] [answered]
Having a problem with FIPS on an ipareplica.

I created 2 EC2 instances from the same AMI.  Both have FIPS enabled.

I ran the cluster playbook with one of them as the ipaserver and the other as an ipareplica.  The server installed just fine, but the replica fails at the step: "ipareplica : Install - Replica preparation"

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ipapython.admintool.ScriptError: Cannot join FIPS-enabled replica into existing topology: FIPS is not enabled on the master server.
fatal: [IDM2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to IDM2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/myuser/.ansible/tmp/ansible-tmp-1691012352.7248142-16788-186937430347613/AnsiballZ_ipareplica_prepare.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/myuser/.ansible/tmp/ansible-tmp-1691012352.7248142-16788-186937430347613/AnsiballZ_ipareplica_prepare.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/myuser/.ansible/tmp/ansible-tmp-1691012352.7248142-16788-186937430347613/AnsiballZ_ipareplica_prepare.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ipareplica_prepare_payload_68zpm0xc/ansible_ipareplica_prepare_payload.zip/ansible/modules/ipareplica_prepare.py\", line 944, in <module>\r\n  File \"/tmp/ansible_ipareplica_prepare_payload_68zpm0xc/ansible_ipareplica_prepare_payload.zip/ansible/modules/ipareplica_prepare.py\", line 627, in main\r\n  File \"/usr/lib/python3.6/site-packages/ipaserver/install/server/replicainstall.py\", line 548, in check_remote_fips_mode\r\n    \"Cannot join FIPS-enabled replica into existing topology: \"\r\nipapython.admintool.ScriptError: Cannot join FIPS-enabled replica into existing topology: FIPS is not enabled on the master server.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

On both the EC2 instances, "crypto.fips_enabled" is set to 1, and the same in /boot/grub2/grub.cfg. They are both RHEL 8.

I am running it by:

ansible-playbook -u myuser -b --private-key ~/.ssh/mykey -i inventory/hosts.cluster playbooks/install-cluster.yml

Inventory file
```
[ipaserver]
IDM1

[ipaserver:vars]
ipaserver_auto_forwarders=no

[ipareplicas_tier1]
IDM2

[ipareplicas_tier2]
IDM3

[ipareplicas_tier3]
IDM4 ipareplica_servers=IDM2,IDM3

[ipareplicas_tier1:vars]
ipaclient_force_join=yes
ipareplica_setup_ca=yes

[ipareplicas_tier2:vars]
ipaclient_force_join=yes

[ipareplicas_tier3:vars]
ipaclient_force_join=yes

[ipaclients]

[ipaclients:vars]
#ipaclient_use_otp=yes
#ipaclient_allow_repair=yes

[ipareplicas:children]
ipareplicas_tier1
ipareplicas_tier2
ipareplicas_tier3

[ipa:children]
ipaserver
ipareplicas
#ipaclients

[ipa:vars]
ipaadmin_password=MyPassword
ipadm_password=MyOtherPassword
ipaserver_domain=MyDomain
ipaserver_realm=MyRealm
ipaserver_setup_dns=no
ipaserver_setup_firewalld=no
```

Playbook
```
---
- name: Install IPA servers
  hosts: ipaserver
  become: true
  roles:
  - role: ipaserver
    state: present

- name: Install IPA replicas Tier1
  hosts: ipareplicas_tier1
  become: true
  roles:
  - role: ipareplica
    state: present

- name: Install IPA replicas Tier2
  hosts: ipareplicas_tier2
  become: true
  roles:
  - role: ipareplica
    state: present

- name: Install IPA replicas Tier3
  hosts: ipareplicas_tier3
  become: true
  roles:
  - role: ipareplica
    state: present
```
