### DISCUSSION TITLE
ipaserver.py module not found

### DISCUSSION THREAD

**Discussion by muksyed1** [freeipa/ansible-freeipa#1341] [Q&A]
I was trying to uninstall freeipa, but I got this error.
fatal: [hostname]: FAILED! => {"reason": "couldn't resolve module/action 'ipaserver'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '~/a
nsible/ansible-freeipa-test/roles/ipaserver/tasks/uninstall.yml': line 33, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  #- name: \"Uninstall - Server del {{ _remove_hostname
 }}\"\n  - name: \"Uninstall - Server del\"\n    ^ here\n"}
Looking at the library - roles/ipaserver/library, I didn't find the ipaserver.py module. 
```
# REMOVE SERVER FROM DOMAIN
  - name: Uninstall - Server del "{{ _remove_hostname }}"
    ipaserver:
      ipaadmin_principal: "{{ ipaadmin_principal | default('admin') }}"
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: "{{ _remove_hostname }}"
      ignore_last_of_role: "{{ ipaserver_ignore_last_of_role }}"
      ignore_topology_disconnect: "{{ ipaserver_ignore_topology_disconnect }}"
      # delete_continue: "{{ ipaserver_delete_continue }}"
      state: absent
    delegate_to: "{{ ipaserver_remove_on_server | default(result_get_connected_server.server) }}"
    when: ipaserver_remove_on_server is defined or
          result_get_connected_server.server is defined
```
Is this really the case? 
Thanks
