### ISSUE TITLE
Using credentials var file with ipa module  ?

### ISSUE THREAD

**Issue by marcosjl** [freeipa/ansible-freeipa#1018]
Hi, 

I'm trying to use a vault file containing admin credentials (as IPA deployment playbooks) for administering IPA.

Here is a typical PB I try to use:

```
---

- name: Playbook to create actual list of users 
  hosts: ipaserver
  remote_user: admin_socle
  become: true
  vars_files:
    - ../IPA-credentials.yml

  tasks:
  - name: Create some user
    freeipa.ansible_freeipa.ipauser:
      state: present
      users:
      - name: foobar
        first: foo
        last: Bar
        uid: 1100
        gid: 1100
        noprivate: true
        homedir: /home/foobar
        loginshell: /bin/bash
        password: "secret"
```

But this does not work. The only way I found to make it work is to add ``ipaadmin_password: <secret>`` in the ipauser task.

I'm using this var file config to successfully deploy IPA server and replicas.

Any hint ?

Regards
José L. Marcos
