### ISSUE TITLE
No installation method or instructions

### ISSUE THREAD

**Issue by JAORMX** [freeipa/ansible-freeipa#11]
There is no setup.py that would help with installation, nor there is documentation on how to install this.

**Comment by dapi** [comment]
Same problem.

Can’t understand how to install this roles.

```playbook
ERROR! the role 'ipaserver' was not found in 
  roles:
    - ipaserver
      ^ here
```

```requirements
- src: https://github.com/freeipa/ansible-freeipa.git
  name: freeipa
```

**Comment by AceBlade258** [comment]
I got it to work by executing my playbook from within the `ansible-freeipa` directory. Not sure what directory it is, but you can probably copy the contents of that folder to one of Ansible's search directories and it would discover the roles automatically.

**Comment by HiTechRabbit** [comment]
Got the same problem.

**Comment by scaronni** [comment]
You can specify additional roles, libraries (module directories), module utilities and action plugins in your ansible configuration. For example in mine:

```
roles_path = external/ansible-freeipa/roles
library = external/ansible-freeipa/library:external/ansible-freeipa/roles/ipaserver/library:external/ansible-freeipa/roles/ipareplica/library
module_utils = external/ansible-freeipa/module_utils
action_plugins = external/ansible-freeipa/action_plugins
```

This is not an issue of this role bundle.

**Comment by mabushey** [comment]
I think the best thing to do is just take the code from https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaserver/tasks/install.yml and refactor it into a proper task yml file. For instance the first item has  `with_items: "{{ ipaserver_packages }}"`. Personally I'm not interested in having that in a var as it's single use. It looks like they used a var because this supports REHL and Ubuntu. I only want Ubuntu.

By removing the role cruft you'll have a simple task that is readable and have a much better understanding of what's actually going on.

Original code that I have no clue how you'd actually run 
```
- name: Install - Ensure that IPA server packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ipaserver_packages }}"

- name: Install - Ensure that IPA server packages for dns are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ipaserver_packages_dns }}"
  when: ipaserver_setup_dns | bool

- name: Install - Ensure that IPA server packages for adtrust are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ipaserver_packages_adtrust }}"
when: ipaserver_setup_adtrust | bool
```

Simple, readable, PORTABLE version of above for Ubuntu:
```
- name: freeipa | Install IPA server packages
  package: name="{{ item }}" state=present
  with_items:
    - freeipa-server
    - freeipa-server-dns
```
