### ISSUE TITLE
Ansible error with external certificates

### ISSUE THREAD

**Issue by mtb-xt** [freeipa/ansible-freeipa#110]
I'm trying to configure freeipa 4.6 on centos 7 using CA-less install and providing my own certs (from LE).

versions:
- ansible-playbook 2.8.2
- CentOS Linux release 7.6.1810 (Core)
- ipa-server-4.6.4-10.el7.centos.3.x86_64

I'm getting this error that I was unable to debug myself:

```
fatal: [ip-10-110-0-169.ap-southeast-2.compute.internal]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
Shared connection to 10.110.0.169 closed.
",
    "module_stdout": "Traceback (most recent call last):
  File \"/home/centos/.ansible/tmp/ansible-tmp-1564441950.3727593-250654284362228/AnsiballZ_ipaserver_test.py\", line 114, in <module>
    _ansiballz_main()
  File \"/home/centos/.ansible/tmp/ansible-tmp-1564441950.3727593-250654284362228/AnsiballZ_ipaserver_test.py\", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/centos/.ansible/tmp/ansible-tmp-1564441950.3727593-250654284362228/AnsiballZ_ipaserver_test.py\", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File \"/tmp/ansible_ipaserver_test_payload_YN3Atn/__main__.py\", line 1060, in <module>
  File \"/tmp/ansible_ipaserver_test_payload_YN3Atn/__main__.py\", line 1056, in main
  File \"/tmp/ansible_ipaserver_test_payload_YN3Atn/ansible_ipaserver_test_payload.zip/ansible/module_utils/basic.py\", line 2046, in exit_json
  File \"/tmp/ansible_ipaserver_test_payload_YN3Atn/ansible_ipaserver_test_payload.zip/ansible/module_utils/basic.py\", line 2039, in _return_formatted
  File \"/tmp/ansible_ipaserver_test_payload_YN3Atn/ansible_ipaserver_test_payload.zip/ansible/module_utils/basic.py\", line 418, in remove_values
  File \"/tmp/ansible_ipaserver_test_payload_YN3Atn/ansible_ipaserver_test_payload.zip/ansible/module_utils/basic.py\", line 401, in _remove_values_conditions
TypeError: Value of unknown type: <type 'instance'>, <open file '<fdopen>', mode 'w+b' at 0x7f79b6cde0c0>
",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by mtb-xt** [comment]
More debug: 

The ipaserver module tries to return this:

```{   '_dirsrv_ca_cert': <ipalib.x509.IPACertificate object at 0x7f5e7d1c5250>,
    '_dirsrv_pkcs12_file': <open file '<fdopen>', mode 'w+b' at 0x7f5e73367db0>,
    '_dirsrv_pkcs12_info': (   '/tmp/tmpyfG2J4',
                               u'<REDACTED>(a password was here)'),
    '_hostname_overridden': True,
    '_http_ca_cert': <ipalib.x509.IPACertificate object at 0x7f5e737b4790>,
    '_http_pkcs12_file': <open file '<fdopen>', mode 'w+b' at 0x7f5e7374d0c0>,
    '_http_pkcs12_info': (   '/tmp/tmp2Sho0x',
                             u'<REDACTED>(a password was here)'),
    '_installation_cleanup': True,
    '_pkinit_ca_cert': None,
    '_pkinit_pkcs12_file': None,
    '_pkinit_pkcs12_info': None,
    'changed': False,
    'domain': 'ipa.<REDACTED>',
    'domainlevel': 1,
    'external_ca': False,
    'external_ca_profile': None,
    'external_ca_type': None,
    'hostname': 'ipa1-au.ipa.<REDACTED>',
    'idmax': 1329599999,
    'idstart': 1329400000,
    'ipa_python_version': 40604,
    'no_host_dns': False,
    'no_pkinit': True,
    'ntp_pool': None,
    'ntp_servers': None,
    'realm': 'IPA.<REDACTED>',
    'rid_base': 1000,
    'secondary_rid_base': 100000000,
    'setup_adtrust': False,
    'setup_ca': False,
    'setup_kra': False}```

and then this trips in this ansible code: /usr/lib/python3.7/site-packages/ansible/module_utils/basic.py:401
```raise TypeError('Value of unknown type: %s, %s' % (type(value), value))```

It doesn't know what to do with a file descriptor. 
If I try to comment out that failure, it just fails next
```
  File \"/usr/lib64/python2.7/json/__init__.py\", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File \"/usr/lib64/python2.7/json/encoder.py\", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File \"/usr/lib64/python2.7/json/encoder.py\", line 270, in iterencode
    return _iterencode(o, 0)
  File \"/tmp/ansible_ipaserver_test_payload_SBfZ_5/ansible_ipaserver_test_payload.zip/ansible/module_utils/common/text/converters.py\", line 28, in _json_encode_fallback
TypeError: Cannot json serialize <open file '<fdopen>', mode 'w+b' at 0x7f20c2d94030>```

**Comment by mtb-xt** [comment]
Some more context:

I'm trying to use a letsencrypt certificate (but can get a regular one if needed) - and I've configured my inventory like that:
I was trying to use regular x509 pem files.
```
all:
  children:
    ipa:
      vars:
        ipaserver_domain: ipa.<redacted>
        ipaserver_realm: IPA.<redacted>
      children:
        ipaserver:
          vars:
            ipaserver_setup_dns: no
            ipaserver_auto_forwarders: no
            ipaserver_no_firewalld: yes
            ipaserver_dirsrv_cert_files: 
               - /etc/letsencrypt/live/ipa.<redacted>/cert.pem
               - /etc/letsencrypt/live/ipa.<redacted>/privkey.pem
            ipaserver_http_cert_files:
               - /etc/letsencrypt/live/ipa.<redacted>/cert.pem
               - /etc/letsencrypt/live/ipa.<redacted>/privkey.pem
            ipaserver_ca_cert_files:
              - /etc/letsencrypt/live/ipa.<redacted>/chain.pem
              - /etc/letsencrypt/live/ipa.<redacted>/isrgrootx1.pem
              - /etc/letsencrypt/live/ipa.<redacted>/letsencryptauthorityx3.pem
            ipaserver_no_pkinit: yes
            ipaserver_dirsrv_pin: ''
            ipaserver_http_pin: ''
        ipareplicas:
          vars:
            ipaclient_domain: ipa.<redacted>
            ipareplica_servers: ipa1-au.ipa.<redacted>
            ipaclient_force_join: yes
            ipareplica_setup_firewalld: no
            ipaserver_no_firewalld: yes
            ipareplica_no_firewalld: yes
            ipareplica_dirsrv_cert_files:
                - /etc/letsencrypt/live/ipa.<redacted>/cert.pem
                - /etc/letsencrypt/live/ipa.<redacted>/privkey.pem
            ipareplica_http_cert_files:
                - /etc/letsencrypt/live/ipa.<redacted>/cert.pem
                - /etc/letsencrypt/live/ipa.<redacted>/privkey.pem
            ipareplica_ca_cert_files:
              - /etc/letsencrypt/live/ipa.<redacted>/chain.pem
              - /etc/letsencrypt/live/ipa.<redacted>/isrgrootx1.pem
              - /etc/letsencrypt/live/ipa.<redacted>/letsencryptauthorityx3.pem
            ipareplica_no_pkinit: yes
            ipareplica_dirsrv_pin: ''
            ipareplica_http_pin: ''
        ipaclients:
```
Then I tried combining them into a pkcs12 file like this:
```
cat fullchain.pem letsencryptauthorityx3.pem  > extrachain.pem
openssl pkcs12 -export -inkey privkey.pem -in extrachain.pem -password pass:12345 -name 'ipa' -caname 'interm' -caname 'ca' -out le.pfx
```

```
all:
  children:
    ipa:
      vars:
        ipaserver_domain: ipa.<redacted>
        ipaserver_realm: IPA.<redacted>
      children:
        ipaserver:
          vars:
            ipaserver_setup_dns: no
            ipaserver_auto_forwarders: no
            ipaserver_no_firewalld: yes
            ipaserver_dirsrv_cert_files: /etc/letsencrypt/live/ipa.<redacted>/le.pfx
            ipaserver_dirsrv_cert_name: ipa
            ipaserver_http_cert_name: ipa               
            ipaserver_http_cert_files: /etc/letsencrypt/live/ipa.<redacted>/le.pfx
            ipaserver_ca_cert_files:
              - /etc/letsencrypt/live/ipa.<redacted>/chain.pem
              - /etc/letsencrypt/live/ipa.<redacted>/isrgrootx1.pem
              - /etc/letsencrypt/live/ipa.<redacted>/letsencryptauthorityx3.pem
            ipaserver_no_pkinit: yes
            ipaserver_dirsrv_pin: '12345'
            ipaserver_http_pin: '12345'
...
```
