### ISSUE TITLE
Correct the playbook in doc for revocation example

### ISSUE THREAD

**Issue by mrizwan93** [freeipa/ansible-freeipa#1132]
playbook mentioned at https://github.com/freeipa/ansible-freeipa/blob/master/README-cert.md
```
---
- name: Revoke certificate
  hosts: ipaserver

  tasks:
  - name Revoke a certificate
    ipacert:
      ipaadmin_password: SomeADMINpassword
      serial_number: 123456789
      state: revoked
```

It doesn't state the revocation reason. Also colon is missing in name directive of `tasks` Correct example playbook would be:

```
---
- name: Revoke certificate
  hosts: ipaserver

  tasks:
  - name: Revoke a certificate
    ipacert:
      ipaadmin_password: SomeADMINpassword
      serial_number: 123456789
      reason: 5
      state: revoked
```
