### ISSUE TITLE
ipadnszone non-idempotent

### ISSUE THREAD

**Issue by adalsa91** [freeipa/ansible-freeipa#1165]
First execution works fine,  subsequent runs fail unless you make changes to any of the variables. I found an issue that I think is related (#862). I understand that the expected result should be that if there are no changes in the definition of the zone, the task returns an OK.

**FreeIPA 4.10.1
ansible-freeipa v1.11.0**

Code:
```yaml
---
- name: Configure DNS zones
  hosts: all
  vars:
    ipaapi_context: client
  tasks:
  - name: Create reverse DNS zones
    ipadnszone:
      ipaadmin_password: "{{ipaadmin_password}}"
      name_from_ip: "192.168.0.1/24"
      allow_sync_ptr: true
      dynamic_update: true
      state: present
```

Error:
```yaml
TASK [Create reverse DNS zones] ************************************************************************************************************************************************************
failed: [host] (item={'network': '192.168.1.0/24'}) => {"ansible_loop_var": "item", "changed": false, "item": {"network": "192.168.1.0/24"}, "msg": "dnszone_mod: 1.168.192.in-addr.arpa.: no modifications to be performed"}
```
