### ISSUE TITLE
ipabackup - ipabackup_name parameter evaluation

### ISSUE THREAD

**Issue by FF186** [freeipa/ansible-freeipa#1198]
Experience error when I try to run ipabackup role twice.

Playbook:
```  
pre_tasks:
    - ansible.builtin.find:
        path: /var/lib/ipa/backup
        file_type: directory
      register: _result

    - set_fact:
        _name: "{{ (_result.files | sort(attribute='path') | first).path }}"

  roles:
    - role: freeipa.ansible_freeipa.ipabackup
      vars:
        state: present

    - role: freeipa.ansible_freeipa.ipabackup
      when: _result.files | length > 5
      vars:
        ipabackup_name: "{{ _name }}"
        state: absent
```

**Error message:**
```
 FAILED! => {"changed": false, "msg": "ipabackup_name is given and state is not copied, restored or absent"}
```
