### ISSUE TITLE
`ipaidp` idempotency fails

### ISSUE THREAD

**Issue by ikerexxe** [freeipa/ansible-freeipa#1210]
I have the following task:
```
    - name: Ensure github idp is present
      ipaidp:
        ipaadmin_password: ****
        name: github
        provider: github
        client_id: ****
        secret: ****
```

The first time I run it, it works correctly. But the second time it fails with:
```
TASK [Ensure github idp is present] ********************************************************************
fatal: [gdm.test]: FAILED! => {"changed": false, "msg": "idp_mod: github: no modifications to be performed"}
```

If there are no modifications to be performed, then it should skip the task.
