### ISSUE TITLE
[ipasmartcard_server] Role to setup Smart card on IPA server should include tuning of SSLOCSPEnable and SSLProtocol

### ISSUE THREAD

**Issue by EmptyByte** [freeipa/ansible-freeipa#1251]
The role to setup smartcard authentication should provide the ability to tune the `SSLOCSPEnable` option and `SSLProtocol` on server:

Refer to the following links for more information:

[Accessing the IPA Web UI in a Web Browser - Red Hat Enterprise Linux 9](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/accessing_identity_management_services/accessing-the-ipa-web-ui-in-a-web-browser_accessing-idm-services#web-browsers-supported-for-accessing-the-web-ui_access-web-ui)

[Bugzilla Report - Bug 1775158](https://bugzilla.redhat.com/show_bug.cgi?id=1775158)

[Getting IPA error when TLS v1.3 is enabled](https://access.redhat.com/solutions/4796941)

```
    - name: Ensure OCSP configuration is set to Leaf
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^\s*#?\s*SSLOCSPEnable\s+.*$'
        line: SSLOCSPEnable leaf
      notify: Restart IPA

    - name: Ensure SSLProtocol excludes SSLv3, TLSv1, TLSv1.1, TLSv1.3
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: '^\s*#?\s*SSLProtocol\s+.*$'
        line: 'SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.3'
        backrefs: yes
      notify: Restart IPA
```
