### ISSUE TITLE
[ipasmartcard_client] Does not include tuning of PAM SSH agent

### ISSUE THREAD

**Issue by EmptyByte** [freeipa/ansible-freeipa#1252]
The role to setup `ipasmartcard_client` does not handle the installation and configuration of PAM SSH agent

Refer to: [Setting up the PAM module for sudo](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/managing_smart_card_authentication/assembly_authenticating-to-sudo-remotely-using-smart-cards_managing-smart-card-authentication#proc_setting-up-the-pam-module-for-sudo_assembly_authenticating-to-sudo-remotely-using-smart-cards)

```yaml
    - name: Ensure PAM SSH agent is installed
      ansible.builtin.dnf:
        name: pam_ssh_agent_auth
        state: present

    - name: Add the authorized_keys_command to /etc/pam.d/sudo
      ansible.builtin.lineinfile:
        path: /etc/pam.d/sudo
        regexp: '^auth\s+sufficient\s+pam_ssh_agent_auth\.so\s+authorized_keys_command=/usr/bin/sss_ssh_authorizedkeys$'
        insertafter: '^#%PAM-1.0$'
        line: 'auth sufficient pam_ssh_agent_auth.so authorized_keys_command=/usr/bin/sss_ssh_authorizedkeys'
        backup: true

    - name: Create sudoers drop-in file for SSH agent forwarding
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ssh_agent_forward
        content: |
          # This file is managed by Ansible
          Defaults env_keep += "SSH_AUTH_SOCK"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
```
