### ISSUE TITLE
[ipasmartcard_client] Does not include configure cockpit

### ISSUE THREAD

**Issue by EmptyByte** [freeipa/ansible-freeipa#1253]
Refer to: [Enabling smart card authentication for the web console](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/managing_smart_card_authentication/configuring-smart-card-authentication-with-the-web-console_managing-smart-card-authentication#enabling-smart-card-authentication-for-the-web-console_configuring-smart-card-authentication-with-the-web-console)

```yaml
    - name: Ensure ClientCertAuthentication is set to yes in /etc/cockpit/cockpit.conf
      community.general.ini_file:
        path: /etc/cockpit/cockpit.conf
        section: WebService
        option: ClientCertAuthentication
        value: yes
        mode: '0600'
        backup: true
```
