### ISSUE TITLE
Key length - how to change

### ISSUE THREAD

**Issue by dracorp** [freeipa/ansible-freeipa#1256]
I'm using ansible-freeipa 1.12.1 installed on Redhat9 with external_ca option.
I got a csr for IPA server but I cannot obtain certificate because of key length:
```
openssl req -in ipa.csr -noout -text | grep "Public-Key"
                Public-Key: (3072 bit)
```
My CA rejects CSRs with "invalid" length.
I need 4096 key length. How I can change this or can I supply my own csr to ansible playbook?

My playbook:
```
---
- name: Playbook to configure IPA server Step 1
  hosts: ipaserver
  become: true
  vars_files:
  - playbook_sensitive_data.yml
  vars:
    ipaserver_external_ca: yes

  roles:
  - role: ipaserver
    state: present

  post_tasks:
  - name: Copy CSR /root/ipa.csr from node to "{{ groups.ipaserver[0] + '-ipa.csr' }}"
    fetch:
      src: /root/ipa.csr
      dest: "{{ groups.ipaserver[0] + '-ipa.csr' }}"
      flat: yes
```

With options:

```
ipaserver_setup_dns=no
ipaserver_external_ca=yes
```
