### ISSUE TITLE
[ipaclient][ipareplica] Include open port checks

### ISSUE THREAD

**Issue by EmptyByte** [freeipa/ansible-freeipa#1266]
Feature request for a task that ensures all ports are open before attempting any installation/modifications:

```yaml
- name: "Ensure required ports are open"
  ansible.builtin.wait_for:
    host: "{{ ipaserver }}"
    port: "{{ item }}"
    state: started
    delay: 0
    timeout: 3
  loop: [80, 88, 389, 464]
```
