### ISSUE TITLE
[role/ipasmartcard_client] Password leaking in cleartext

### ISSUE THREAD

**Issue by EmptyByte** [freeipa/ansible-freeipa#1278]
In the following task:
```
  - name: Authenticate using kinit with password for "{{ ipaadmin_principal }}"
    ansible.builtin.command: kinit "{{ ipaadmin_principal }}"
    args:
      stdin: "{{ ipaadmin_password }}"
    when: ipaadmin_password is defined
```

Please add a `no_log: true`.
