### ISSUE TITLE
install-client playbook - No module named 'ipapython'

### ISSUE THREAD

**Issue by dracorp** [freeipa/ansible-freeipa#1279]
I'm working in RHEL9 with installed ansible-freeipa-1.12.1-1.el9.noarch. But it also occurs with cloned the repository.
I've successful installed server, replica, and two clients using installed package. Then I've prepared my playbook with customization to install client on dedicated hosts because I have a lot of broken or outdated VMs. The playbook:
```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - assert:
        that:
          - target is defined
        fail_msg: "The 'target' has to be defined."
        success_msg: "The 'target' variable is properly defined."
        quiet: true

- name: Add the target host dynamically
  hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        name: '{{target}}'
        groups: ipaclients

- name: Playbook to prepare IPA clients
  hosts: '{{target}}'
  gather_facts: true
  tasks:
    - name: Run pre-install
      include_tasks: ../roles/idm-install-client/tasks/pre-install.yml

- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  become: true

  roles:
  - role: ipaclient
    state: present

- name: Playbook to post-install configuration IPA clients
  hosts: ipaclients
  gather_facts: false
  roles:
    - role: idm-install-client
```
**ansible.cfg**:
```
[defaults]
inventory               = inventory/hosts.ini
```

**../roles/idm-install-client/tasks/pre-install.yml**:
```
---
- name: Load secret variables
  ansible.builtin.include_vars:
    file: ../vars/secrets.yml
  tags: always

- name: Configure CentOS repositories
  ansible.builtin.import_role:
    name: commons
    tasks_from: config-CentOS7-repository
  when: ansible_distribution == 'CentOS'

- name: Clean docker
  shell: |
    docker system prune -af
    docker volume prune -af
```
I'm not sure about **../vars/secrets.yml**. It contains ipaadmin_password, and ipadm_password. The role idm-install-client does the customization.

When I invoke the playbook:
```
# ansible-playbook playbooks/idm-install-client.yml -e target=node7
PLAY [localhost] ********************************************************************************************************************************************

TASK [assert] ***********************************************************************************************************************************************
ok: [localhost]

PLAY [Add the target host dynamically] **********************************************************************************************************************

TASK [add_host] *********************************************************************************************************************************************
ok: [localhost]

PLAY [Playbook to prepare IPA clients] **********************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [node7]

TASK [Run pre-install] **************************************************************************************************************************************
included: /root/MyPlaybooks/jenkins-lido-cicd-ansible-ops/roles/idm-install-client/tasks/pre-install.yml for node7

TASK [Load secret variables] ********************************************************************************************************************************
ok: [node7]

TASK [commons : Copy Centos Base repository] ****************************************************************************************************************
ok: [node7]

TASK [Clean docker] *****************************************************************************************************************************************
	changed: [node7]

PLAY [Playbook to configure IPA clients with username/password] *********************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [node7]

TASK [ipaclient : Import variables specific to distribution] ************************************************************************************************
ok: [node7] => (item=/usr/share/ansible/roles/ipaclient/vars/RedHat-7.yml)

TASK [ipaclient : Install IPA client] ***********************************************************************************************************************
included: /usr/share/ansible/roles/ipaclient/tasks/install.yml for node7

TASK [ipaclient : Install - Ensure that IPA client packages are installed] **********************************************************************************
ok: [node7]

TASK [ipaclient : Install - Set ipaclient_servers] **********************************************************************************************************
skipping: [node7]

TASK [ipaclient : Install - Set ipaclient_servers from cluster inventory] ***********************************************************************************
skipping: [node7]

TASK [ipaclient : Install - Check that either password or keytab is set] ************************************************************************************
skipping: [node7]

TASK [ipaclient : Install - Set default principal if no keytab is given] ************************************************************************************
ok: [node7]

TASK [ipaclient : Install - Fail on missing ipaclient_domain and ipaserver_domain] **************************************************************************
skipping: [node7]

TASK [ipaclient : Install - Fail on missing ipaclient_servers] **********************************************************************************************
skipping: [node7]

TASK [ipaclient : Install - Configure DNS resolver] *********************************************************************************************************
skipping: [node7]

TASK [ipaclient : Install - IPA client test] ****************************************************************************************************************
fatal: [node7]: FAILED! => {"changed": false, "msg": "No module named 'ipapython'"}

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
node7                      : ok=10   changed=1    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0
```

Why? What is wrong with my playbook?
