### ISSUE TITLE
When using multiple groups, ipagroup is not idempotent.

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#1291]
Due to the way values are extracted from the groups dictionary, case insensitive fields are incorrectly evaluated.

The folowing playbook snippet fails on the second task with `group_add_member: user USER01: This entry is already a member'`

```yaml
- name: Add group.
  ipagroup:
    groups:
      - name: group01
        users: user01
- name: Add group, again.
  ipagroup:
    groups:
      - name: group01
        users: USER01
```

All modules with support for multiple object modifications should be reviewed (e.g.: ipaservice), as this issue may also happen on those.
