### ISSUE TITLE
ipareplica and ipaclient fail when there are more than on deployment set in an inventory file

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#1326]
When you have more than one deployment define in an inventory file, you can select the hosts to run the playbooks against with something like `ipareplicas:&{{ run_here }}`.

The problem is that when defining the server list for both `ipareplica` and `ipaclient` roles forces a query to the inventory file without the filter in place.

See the tasks from `ipareplica`:

```yaml
- name: Install - Set ipareplica_servers
  ansible.builtin.set_fact:
    ipareplica_servers: "{{ groups['ipaservers'] | list }}"
  when: groups.ipaservers is defined and ipareplica_servers is not defined

- name: Install - Set ipareplica_servers from cluster inventory
  ansible.builtin.set_fact:
    ipareplica_servers: "{{ groups['ipaserver'] | list }}"
  when: ipareplica_servers is not defined and groups.ipaserver is defined
```

The workaround for this issue is to have `ipareplica_servers` and `ipaclient_servers` set.

Today, it is not a huge issue as a single deployment is expected, but with IPA-to-IPA migration in place, we may face the same issue as multiple deployments in one inventory file may become more common.
