### ISSUE TITLE
Install ipaserver - gets stuck on Install Setup CA

### ISSUE THREAD

**Issue by sovereignlight2019** [freeipa/ansible-freeipa#149]
I am trying to install a master server and I keep running into this issue

Using RHEL7.6 for the master
Ansible 2.9 on MacOS (Homebrew)
Python 3.7.5

My inventory looks as follows 

```
    ipaservers:
      hosts:
        rhel7-host1.test.sovereignlight.solutions:
      vars:
        ipaadmin_user: admin
        ipadm_password: MySecretPassword123
        ipaadmin_password: MySecretPassword234
        ipaserver_domain: test.sovereignlight.solutions
        ipaserver_realm: TEST.SOVEREIGNLIGHT.SOLUTIONS
        ipaserver_install_packages: true
        ipaserver_setup_firewalld: false
        ipaserver_setup_dns: true
        ipaserver_auto_forwarders: yes
        ipaserver_no_host_dns: yes
        #ipaserver_hostname: rhel7-host1.test.sovereignlight.solutions
        #ipaserver_forwarders: 8.8.8.8
        #ipaserver_setup_adtrust: no
        #ipaserver_setup_kra: no
        #ipaserver_enable_compat: no
        #ipaserver_netbios_name:
        #ipaserver_rid_base:
        #ipaserver_secondary_rid_base:
```
The error in /var/log/messages:

```
Nov 20 13:24:56 rhel7-host1 server: Internal Database Error encountered: Could not connect to LDAP server host rhel7-host1.test.sovereignlight.solutions port 636 Error netscape.ldap.LDAPException: Authentication failed (48)
Nov 20 13:25:06 rhel7-host1 server: WARNING: Exception processing realm com.netscape.cms.tomcat.ProxyRealm@2aa0b78d background process
Nov 20 13:25:06 rhel7-host1 server: javax.ws.rs.ServiceUnavailableException: Subsystem unavailable
```

> PKI tomcat service fails to start with the error message in /var/log/pki/pki-tomcat/ca/debug 

`Internal Database Error encountered: Could not connect to LDAP server host rhel7-host1.test.sovereignlight.solutions port 636 Error netscape.ldap.LDAPException: Authentication failed (48)`

**Comment by t-woerner** [comment]
There are two differences in your command line: You are stting the hostname and you are enabling auto-reverse. Please add these settings also to your inventory file. There is also a ":" in "rhel7-host1.test.sovereignlight.solutions:" in your inventory.

**Comment by sovereignlight2019** [comment]
The additional command line settings made no difference.

However, changing from a yaml inventory to an ini inventory ...  it then worked.
I did that because ansible will not allow removing the : after the hostname entry.

Before :

```
    ipaserver:
      hosts:
        rhel7-host1.test.sovereignlight.solutions:
      vars:
        ipaadmin_user: admin
        ipadm_password: MySecretPassword123
        ipaadmin_password: MySecretPassword234
        ipaserver_domain: test.sovereignlight.solutions
        ipaserver_realm: TEST.SOVEREIGNLIGHT.SOLUTIONS
        ipaserver_install_packages: true
        ipaserver_setup_firewalld: false
        ipaserver_setup_dns: true
        ipaserver_auto_forwarders: yes
        ipaserver_no_host_dns: yes
        #ipaserver_hostname: rhel7-host1.test.sovereignlight.solutions
        #ipaserver_forwarders: 8.8.8.8
        #ipaserver_setup_adtrust: no
        #ipaserver_setup_kra: no
        #ipaserver_enable_compat: no
        #ipaserver_netbios_name:
        #ipaserver_rid_base:
        #ipaserver_secondary_rid_base:
```
After: 

```
[ipaserver]
rhel7-host1.test.sovereignlight.solutions
[ipaserver:vars]
ipaadmin_user=admin
ipadm_password=MySecretPassword123
ipaadmin_password=MySecretPassword234
ipaserver_domain=test.sovereignlight.solutions
ipaserver_realm=TEST.SOVEREIGNLIGHT.SOLUTIONS
ipaserver_install_packages=true
ipaserver_setup_firewalld=false
ipaserver_setup_dns=true
ipaserver_auto_forwarders=yes
ipaserver_no_host_dns=yes
#ipaserver_hostname=rhel7-host1.test.sovereignlight.solutions
#ipaserver_forwarders=8.8.8.8
#ipaserver_setup_adtrust=no
#ipaserver_setup_kra=no
#ipaserver_enable_compat=no
#ipaserver_netbios_name:
#ipaserver_rid_base:
#ipaserver_secondary_rid_base:
```

might be a bug.
