### ISSUE TITLE
ipagroup module not idempotent, it breaks on second run when external is true

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#159]
Hello,

When creating an ipagroup with externa set to true, it breaks the second time the play is run.
Error:
 This group already allows external members

run a play with this task twice and it will break on the second run
```
  - name: add external mapping group
    ipagroup:
      ipaadmin_password: '{{ ipaadmin_password }}'
      name: ad_domain_admins_external
      description: AD domain admins external map
      external: true
```
it fails with the error:
` "msg": "group_mod: ad_admins_external: This group already allows external members"`
