### ISSUE TITLE
Do not require PTR be same

### ISSUE THREAD

**Issue by jirib** [freeipa/ansible-freeipa#190]
ansible-freeipa git version: `499e738509abc0e16b693d49abb607e1183cd1a0`

In following scenario we have PTR managed by consul, thus `ipareplica_hostname` does not match name got from PTR.

```
[root@ipa3 ~]# hostname
ipa3.example.com
[root@ipa3 ~]# dig +noall +answer `hostname`. A
ipa3.example.com.         3246    IN      A       10.72.0.93
[root@ipa3 ~]# dig +noall +answer -x 10.72.0.93
93.0.72.10.in-addr.arpa. 0      IN      PTR     ipa3.node.prod.consul.
```
We use `aws_ec2.yml` plugin (AWS here), and `inventory_hostname` is `ipa3.example.com`.

```
    # workaround because by default ipaclient role uses ansible_fqdn which is
    # based on PTR, see https://bit.ly/2Rkbu39        
    - name: Import upstream ansible-freeipa ipareplica role
      import_role:
        name: freeipa/ansible-freeipa/roles/ipareplica
      vars:
        ipareplica_hostname: "{{ inventory_hostname }}"
        state: present
```
Workaround: I edited `/etc/hosts`.

```
An exception occurred during task execution. To see the full
traceback, use -vvv. The error was:
ipaserver.install.installutils.HostLookupError: The host name
ipa3.example.com does not match the primary host name
ipa3.node.prod.consul. Please check /etc/hosts or DNS name resolution
fatal: [ipa3.example.com]: FAILED! => {"changed": false,
"module_stderr": "Traceback (most recent call last):\n File
\"<stdin>\", line 102, in <module>\n File \"<stdin>\", line 94, in
_ansiballz_main\n File \"<stdin>\", line 40, in invoke_module\n File
\"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n fname,
loader, pkg_name)\n File \"/usr/lib64/python2.7/runpy.py\", line 82,
in _run_module_code\n mod_name, mod_fname, mod_loader, pkg_name)\n
File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n exec
code in run_globals\n File
\"/tmp/ansible_ipareplica_prepare_payload_dVI_JP/ansible_ipareplica_prepare_payload.zip/ansible/modules/ipareplica_prepare.py\",
line 2068, in <module>\n File
\"/tmp/ansible_ipareplica_prepare_payload_dVI_JP/ansible_ipareplica_prepare_payload.zip/ansible/modules/ipareplica_prepare.py\",
line 1716, in main\n File
\"/usr/lib/python2.7/site-packages/ipaserver/install/installutils.py\",
line 179, in verify_fqdn\n \"Please check /etc/hosts or DNS name
resolution\" % (host_name,
ex_name[0]))\nipaserver.install.installutils.HostLookupError: The host
name ipa3.example.com does not match the primary host name
ipa3.node.prod.consul. Please check /etc/hosts or DNS name
resolution\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee
stdout/stderr for the exact error", "rc": 1}
```

**Comment by rjeffman** [comment]
This scenario is expected, as FreeIPA requires that the reverse address matches the hostname.

Form the [FreeIPA documentation](https://www.freeipa.org/page/Quick_Start_Guide#Preparing_a_Platform):

>The IPA installer is quite picky about the DNS configuration. The following checks are done by installer:
    - The hostname cannot be localhost or localhost6.
    - The hostname must be fully-qualified (ipa.example.com)
    - The hostname must be resolvable.
    - The reverse of address that it resolves to must match the hostname.

I once had this problem with AWS, and used the following to obtain the reverse hostname:

```yaml
- name: Retrieve idmserver DNS name.
  hosts: YOUR_INVENTORY_HOST
  become: yes
  gather_facts: yes
  tasks:
    - name: Ensure `dig` is available.
      package:
        name: bind-utils
        state: present
    - name: Retrieve hostname from IP address.
      command: dig +short +onesoa -x "{{ ansible_default_ipv4.address }}"
      register: dig_out
    - name: Provide reverse_hostname fact.
      set_fact:
        reverse_hostname: "{{ dig_out.stdout_lines[0][:-1] }}"
```

Then, you can use `reverse_hostname` fact whenever you need the IPA sever hostname.
