### ISSUE TITLE
Host module fails with variable `reverse: yes`

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#226]
When using the host module with the reverse option set to true I'm having, consistently, this error:

```
TASK [Host "host1.ipademo.local" present] **************************************
fatal: [server81.ipademo.local]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "dnsrecord_add: ipademo.local: 'aaaarecord' is required"}
```
The playbook used to test is:
```yaml
---
- name: Test host
  hosts: ipaserver
  become: true
  gather_facts: true

  - name: Host host1.ipademo.local present
      ipahost:
        ipaadmin_password: SomeADMINpassword
        name: host1.ipademo.local
        ip_address: 192.168.122.201
        update_dns: yes
        reverse: yes
```
