### ISSUE TITLE
install-client doesn't result in a client that can be logged into

### ISSUE THREAD

**Issue by datakid** [freeipa/ansible-freeipa#23]
We have a working one way trust with an AD installation. 

When I install ipa-client via ipa-client-install, I have a system in which I can login to successfully.

When I install ipa-client via ansible install-client.yml, I have a system into which I can't login successfully.

First diff found was in /var/log/sssd/sssd_pam.log. 
On the working system:
```
(Tue May  8 10:54:20 2018) [sssd[pam]] [pam_dom_forwarder] (0x0100): pam_dp_send_req returned 0
(Tue May  8 10:54:20 2018) [sssd[pam]] [pam_dp_process_reply] (0x0200): received: [14 (Cannot make/remove an entry for the specified session)][company.com]
(Tue May  8 10:54:20 2018) [sssd[pam]] [pam_reply] (0x0200): pam_reply called with result [14]: Cannot make/remove an entry for the specified session.
(Tue May  8 10:54:20 2018) [sssd[pam]] [filter_responses] (0x0100): [pam_response_filter] not available, not fatal.
(Tue May  8 10:54:20 2018) [sssd[pam]] [pam_reply] (0x0200): blen: 32
```

On the not working system:

```
(Tue May  8 11:14:22 2018) [sssd[pam]] [pam_dom_forwarder] (0x0100): pam_dp_send_req returned 0
(Tue May  8 11:14:22 2018) [sssd[pam]] [pam_dp_process_reply] (0x0200): received: [9 (Authentication service cannot retrieve authentication info)][company.com]
(Tue May  8 11:14:22 2018) [sssd[pam]] [pam_reply] (0x0200): pam_reply called with result [9]: Authentication service cannot retrieve authentication info.
(Tue May  8 11:14:22 2018) [sssd[pam]] [pam_reply] (0x0020): Unknown PAM call [249].
(Tue May  8 11:14:22 2018) [sssd[pam]] [filter_responses] (0x0100): [pam_response_filter] not available, not fatal.
(Tue May  8 11:14:22 2018) [sssd[pam]] [pam_reply] (0x0200): blen: 32
(Tue May  8 11:14:23 2018) [sssd[pam]] [client_recv] (0x0200): Client disconnected!
```
After following [some dead ends](https://access.redhat.com/solutions/342953)  I worked through each stanza of the -vv verbose anisble output and saw /etc/krb.conf

When comparing the two, there are significant differences (this playbook is very comprehensive by comparison).
Most importantly, it was the [two default](https://github.com/freeipa/ansible-freeipa/blob/master/roles/krb5/defaults/main.yml) values
```
krb5_dns_lookup_realm: "false"
krb5_dns_lookup_kdc: "false"
```
that were causing the issue. This differs from a standard installation which normally has them as true.

From what I can see, this is set in this [install.yml](https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaclient/tasks/install.yml) when `ipadiscovery.dnsok` fails. 
```
  - name: Install - Configure krb5 for IPA realm "{{ ipadiscovery.realm }} <= 4.4"
    include_role:
      name: krb5
    vars:
      krb5_servers: "{{ [ ] if ipadiscovery.dnsok else ipadiscovery.servers }}"
      krb5_realm: "{{ ipadiscovery.realm }}"
      krb5_dns_lookup_realm: "{{ 'true' if ipadiscovery.dnsok else 'false' }}"
      krb5_dns_lookup_kdc: "{{ 'true' if ipadiscovery.dnsok else 'false' }}"
      krb5_no_default_domain: "{{ 'true' if ipadiscovery.domain != ipadiscovery.client_domain else 'false' }}"
      krb5_pkinit_anchors: "FILE:/etc/ipa/ca.crt"
    when: not ipaclient_on_master | bool and ipadiscovery.ipa_python_version <= 40400
```

Why does this happen in the ansible playbook but not a regular ipa-client-install?

It looks like ipadiscovery.dnsok is set by [library/ipadiscovery.py](https://github.com/freeipa/ansible-freeipa/blob/d009b80621244d447ca5d52aeac1cae7bc4499e1/library/ipadiscovery.py) on line 348
```
    else:
        # Only set dnsok to True if we were not passed in one or more servers
        # and if DNS discovery actually worked.
        if not opt_servers:
            (server, domain) = ds.check_domain(
                ds.domain, set(), "Validating DNS Discovery")
            if server and domain:
                module.debug("DNS validated, enabling discovery")
                dnsok = True
```

Why does this not work for ansible but it does for ipa-client-install?
