### ISSUE TITLE
ipahost is not idempotent 

### ISSUE THREAD

**Issue by itcultus** [freeipa/ansible-freeipa#253]
I try to establish this workflow: 

1st Run: 
Register Host in IdM and get OTP --> Install ipa-client with this OTP

n run: 
Verify that the host is register in IdM no OTP --> ipa-client already install, continue

However, it looks like the ipahost is not idempotent and thus I cannot run it like this. 
The problems I see are: 
1. If the host in question is not enrolled in IdM, I get a new OTP **always**. 
1. If the host is enrolled I get the following error: 

```
fatal: [idm_master.example.com]: FAILED! => changed=false 
  msg: 'host_mod: new_host.example.com: invalid ''password'': Password cannot be set on enrolled host.'
```
However, I do **not** set any password!

This is my playbook: 

```yaml
    - name: Create Host in IdM
      freeipa.ansible_freeipa.ipahost:
        ipaadmin_principal: "{{ admin_principal }}"
        ipaadmin_password: "{{ admin_password }}"
        name: "{{ new_server }}"
        description: "{{ new_server_description }}"
        random: true
        update_dns: false
        force: false
        state: present
        update_password: on_create
      register: host_otp
```
 The debug output is the following: 

```yaml
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_NLGXvr/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipahost.py", line 1334, in main
  File "/tmp/ansible_freeipa.ansible_freeipa.ipahost_payload_NLGXvr/ansible_freeipa.ansible_freeipa.ipahost_payload.zip/ansible/module_utils/ansible_freeipa_module.py", line 153, in api_command
    return api.Command[command](name, **args)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 450, in __call__
    return self.__do_call(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 478, in __do_call
    ret = self.run(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 800, in run
    return self.execute(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipaserver/plugins/baseldap.py", line 1425, in execute
    *keys, **options)
  File "/usr/lib/python2.7/site-packages/ipaserver/plugins/host.py", line 869, in pre_callback
    error=_('Password cannot be set on enrolled host.'))
[WARNING]: Module did not set no_log for update_password
fatal: idm_master.example.com]: FAILED! => changed=false 
  invocation:
    module_args:
      action: host
      allow_create_keytab_group: null
      allow_create_keytab_host: null
      allow_create_keytab_hostgroup: null
      allow_create_keytab_user: null
      allow_retrieve_keytab_group: null
      allow_retrieve_keytab_host: null
      allow_retrieve_keytab_hostgroup: null
      allow_retrieve_keytab_user: null
      auth_ind: null
      certificate: null
      description: Host Description
      force: false
      hosts: null
      ip_address: null
      ipaadmin_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      ipaadmin_principal: admin@EXAMPLE.COM
      locality: null
      location: null
      mac_address: null
      managedby_host: null
      name:
      - new_host.example.com
      ok_as_delegate: null
      ok_to_auth_as_delegate: null
      os: null
      password: null
      platform: null
      principal: null
      random: true
      requires_pre_auth: null
      reverse: null
      sshpubkey: null
      state: present
      update_dns: false
      update_password: on_create
      userclass: null
  msg: 'host_mod: new_host.example.com: invalid ''password'': Password cannot be set on enrolled host.'
```
As you can see, there it password set, so I am suspecting a bug. 

My controller node is Fedora 31 with Ansible 2.9.6 and the IdM is on a RHEL 7.7:

```
ipa --version
VERSION: 4.6.5, API_VERSION: 2.231
```
