### ISSUE TITLE
ipaserver install playbook fails

### ISSUE THREAD

**Issue by darkodo** [freeipa/ansible-freeipa#258]
When using ansible to install FreeIPA on CentOS 8.1, the installation fails showing the following message: 
````
TASK [ipaclient : Install - IPA client test] ***************************************************************
fatal: [freeipa.domain.tld]: FAILED! => {"changed": false, "msg": "Failed to verify that freeipa.domain.tld is an IPA Server."} 
````

I used this playbook:
````
- hosts: ipaserver
  become: yes
  roles:
    - role: ipaserver
      vars:
        ipaserver_hostname: freeipa.domain.tld
        ipaserver_domain: domain.tld
        ipaserver_realm: domain.tld
        ipaserver_setup_dns: yes
        ipaserver_auto_forwarders: yes                                                                                                
        ipadm_password: 'pass1'
        ipaadmin_password: 'pass2'
````

If I try to visit freeipa.domain.tld, the site is unresponsive.

If I install FreeIPA server manually with `ipa-server-install --setup-dns` though, it works fine.

**Comment by jswindle-rtn** [comment]
Looks like a configuration problem to me.
1. Is there an external DNS? auto_forwarders: yes implies that you have nameservers in /etc/resolv.conf
2. Will the external DNS resolve FreeIPA.domain.tld? 
3. If external DNS doesn't resolve FreeIPA.domain.tld, is it in your /etc/hosts?
This is what I use for an external DNS that will not resolve FreeIPA.domain.tld
`ipaserver_auto_forwarders: yes
ipaserver_no_forwarders: no
ipaserver_no_host_dns: true
ipaserver_setup_dns: yes
`

**Comment by darkodo** [comment]
Thanks for your reply, it is effectively a DNS issue.

I managed to have a working playbook using `ipaserver_forwarders` parameter.
Neither the parameters `ipaserver_auto_forwarders` or `ipaserver_no_forwarders` worked for me.

The working playbook:
````
---
- hosts: ipaserver
  become: yes
  vars:
    the_hostname: freeipa.net.localnet
    the_domain: net.localnet

  pre_tasks:
    - name: Set hostname
      hostname:
        name: "{{ the_hostname }}"

    - name: Put hostname in /etc/hosts                                                                                                                                                                            
      lineinfile:
        line: "{{ ansible_default_ipv4.address }}  {{ the_hostname }}"
        path: /etc/hosts
        state: present

  roles:                                                                                                                                                                          
    - role: ipaserver
      vars:
        ipaserver_hostname: "{{ the_hostname }}"
        ipaserver_domain: "{{ the_domain }}"
        ipaserver_realm: "{{ the_domain|upper }}"
        ipaserver_setup_dns: yes
        ipaserver_auto_forwarders: false                                                                                                                                                                          
        ipaserver_no_forwarders: false
        ipaserver_forwarders: '192.168.1.2'
        ipaserver_no_host_dns: true                                                                                             
        ipadm_password: '123456789'
        ipaadmin_password: '123456789'
````

It is strange behaviour as in _/etc/resolv.conf_ it is the same name server, so  `ipaserver_auto_forwarders` should works too.
