### ISSUE TITLE
documentation request

### ISSUE THREAD

**Issue by beargiles** [freeipa/ansible-freeipa#265]
It took me a surprisingly long time to put the pieces together so it would probably help others to add a bit of documentation on the README. The problem is because of the collections - they're so new it took me a long time to figure out the correct 'role'. The fact that molecule listed the *roles* directories being search but no *collections* directories didn't help. 

I'm still trying to get this to work in a molecule test. I don't know if it's a configuration error on my side, a misconfiguration of the platform, the role simply not working on docker, etc.

Play to install IPA Server

```
- name: install freeipa
  vars:
    # base variables
    ipaserver: '{{ fqdn }}'
    ipadm_password: '{{ dm_password }}'
    ipaadmin_password: '{{ admin_password }}'
    ipaserver_domain: '{{ domain }}'
    ipaserver_realm: '{{ domain | upper }}'
    ipaserver_hostname: '{{ fqdn }}'

    # server variables
    ipaserver_setup_kra: yes
    ipaserver_setup_dns: yes
    # ipaserver_dirsrv_config_file: ldif file
    # ipaserver_pki_config_override:

    # client variables
    ipaclient_mkhomedir: yes

    # certificate system variables
    ipaserver_subject_base: '{{ subject_base }}'
    ipaserver_ca_subject: '{{ ca_subject }}'

    # dns variables
    ipaserver_auto_reverse: yes
    ipaserver_auto_forwarders: yes

    # special variables
    ipaserver_setup_firewalld: no
  import_role:
    name: freeipa.ansible_freeipa.ipaserver
```

and

```
#
# FreeIPA information
#
admin_password: password

#
# DNS information
#
hostname: ipa
domain: example.com
fqdn: '{{ hostname }}.{{ domain }}'

#
# LDAP/Directory Services information
# The 'subject_base' should match the 'domain'
#
dm_password: password
subject_base: 'dc=example,dc=com'
ca_subject: 'cn=Certificate Authority,{{ subject_base }}'
```
