### ISSUE TITLE
ipaserver role fails in IPA client test

### ISSUE THREAD

**Issue by diniguezcabrera** [freeipa/ansible-freeipa#273]
I'm having an error when I run the ipaserver role from my local to a remote server (future ipaserver)
I'm using Centos 8

```
TASK [ipaclient : Install - IPA client test] ***************************************************************
fatal: [freeipa.domain.com]: FAILED! => {"changed": false, "msg": "Failed to verify that freeipa.domain.com is an IPA Server."}
``` 
My playbook

```
- hosts: ipaservers
  become: yes
  roles:
    - role: ipaserver
      state: present
      vars:
        ipaserver_hostname: freeipa1.domain.com
        ipaserver_domain: domain.com
        ipaserver_realm: domain.com
        ipaadmin_password: UltraS3cure
        ipadm_password: UltraS3cure 
```
When I try to visit freeipa1.domain.com the site is unresponsive.

I saw the issue #258 were the solution was to use install dns options but **I need to use an external DNS**. I tried with the following playbook:

 ```
- hosts: ipaservers
  become: yes
  roles:
    - role: ipaserver
      state: present
      vars:
        ipaserver_hostname: freeipa1.domain.com
        ipaserver_domain: domain.com
        ipaserver_realm: domain.com
        ipaadmin_password: UltraS3cure
        ipadm_password: UltraS3cure
        ipaserver_setup_dns: yes
        ipaserver_auto_forwarders: yes
```
I used this, because the documentation of the role includes it https://github.com/freeipa/ansible-freeipa/tree/master/roles/ipaserver#usage

The remote server has the DNS nameservers in its resolv.conf.

I also tried with these parameters but with no result:

```
        ipaserver_setup_dns: yes
        ipaserver_auto_forwarders: yes 
        ipaserver_no_forwarders: no
        ipaserver_no_host_dns: true
```
With the following error

```
TASK [ipaserver : Install - Server preparation] *******************************************************************************************************************************************************************
fatal: [freeipa1]: FAILED! => {"changed": false, "msg": "DNS zone domain.com. already exists in DNS and is handled by server(s): server1.domain.com., server2.domain.com., server3.domain.com."}
```
This DNS servers exists and handle the zone and the DNS.

Maybe I can skip the dns installation step or something?

The manual installation works.
