### ISSUE TITLE
Server installation test fails

### ISSUE THREAD

**Issue by unitynet-dk** [freeipa/ansible-freeipa#297]
Hi developers
I can't really make the installation of the FreeIPA server work. An error persists during server installation testing:
"An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: ansible_collections.freeipa.ansible_freeipa.plugins.module_utils.ansible_ipa_server.__spec__ is None
fatal: [auth]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}"
I have tried installing under Ubuntu 16.04 and 18.04 as well as CentOS 7. They all fail in the same place.
Somewhere I read that the installation should work with python 2.7, but I can't make it work either.

Yours sincerely
Søren Sjøstrøm
Unitynet

**Comment by t-woerner** [comment]
Which ansible and ansible-freeipa version do you have?

**Comment by unitynet-dk** [comment]
Hi

Thanks for your reply.

I’m using Ansible version 2.9.2 and ansible-freeipa version 0.1.10 (the one from ansible-galaxy).

**Comment by t-woerner** [comment]
Which operation system do you use on the controller? How have you installed ansible on the controller?

I am able to use the collection with ansible 2.9.6 on my Fedora-32 controller without issues to deploy CentOS-7 and RHEL-8 machines. I even tried different ways:

```
---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
```

and

```
---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true

  collections:
  - freeipa.ansible_freeipa

  tasks:
  - name: Deploy server
    include_role:
      name: ipaserver
```
