### ISSUE TITLE
[Role handling] Not able to add role with space

### ISSUE THREAD

**Issue by varunmylaraiah** [freeipa/ansible-freeipa#408]
Space is not allowed in the role name.

```
[root@ansible ~]# cat role05a.yaml
---
- name: "Add role with space"
  hosts: ipaserver

  tasks:
  - iparole:
      ipaadmin_password: <password>
      name: "user, hostgroup new rule"
      description: A role in IPA.

```
```
[root@ansible ~]# ansible-playbook -vv -i inventory/server.hosts role05a.yaml 
ansible-playbook 2.9.11
  config file = /root/ansible.cfg
  configured module search path = ['/root/ansible-freeipa/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
Using /root/ansible.cfg as config file

PLAYBOOK: role05a.yaml ***********************************************************************************************
1 plays in role05a.yaml

PLAY [Add role with space]
 *****************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
task path: /root/role05a.yaml:2
[DEPRECATION WARNING]: Distribution fedora 32 on host master.ipadomain.test should use /usr/bin/python3, but is using
 /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to 
using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
ok: [master.ipadomain.test]
META: ran handlers

TASK [iparole] *******************************************************************************************************
task path: /root/role05a.yaml:6
fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "role_add:  hostgroup new rule: invalid 'name': Leading and trailing spaces are not allowed"}

PLAY RECAP ***********************************************************************************************************
master.ipadomain.test      : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

Actual results:
FAILED! => {"changed": false, "msg": "role_add:  hostgroup new rule: invalid 'name': Leading and trailing spaces are not allowed"}

```
Expected results:
CLI Console output
```
[root@master ~]# ipa role-add "user, group new rule"
---------------------------------
Added role "user, group new rule"
---------------------------------
  Role name: user, group new rule

```

**Comment by rjeffman** [comment]
Although there is an issue (or two) related to this type of `name` for the `iparole`, in this specific case, the problem is the playbook.

As `name` is a list, Ansible converts the given input in two "names": `"user` and ` host hostgroup new rule"`, which is not what I believe is wanted from this playbook.

If you use the following playbook, the test succeeds:
```yaml
---
- name: "Add role with space"
  hosts: ipaserver

  tasks:
  - name: update role.
    iparole:
      ipaadmin_password: <password>
      name:
      - user, hostgroup new rule
```

With this syntax for lists, each item is an entry, making Ansible respect that the comma is part of the name.

Thank you for the report, as I found issues on updating a role with this kind of name (with spaces, commas), and with comma separated lists. A fix for these is being worked on.
