### ISSUE TITLE
ipasudcmdgroup a 2 stage operation?

### ISSUE THREAD

**Issue by chsnell** [freeipa/ansible-freeipa#440]
From my testing, it appears that the ipasudocmdgroup appears to be a 2 stage command:
1. you have to create the group
2. then you have to populate the actual commands in the group

If I try do do these all in one step, I get varying failures.  If I run a stanza like this:

- name: Ensure sudo command groups are present
  ipasudocmdgroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ item.name }}"
    sudocmd: "{{ item.commands }}"
  loop: "{{ sudo_cmdgrps }}"

the groups get created, but no commands are added to the command groups.

If I add the 'action: member' option, it needs the group to exist first and errors out completely.

Can someone confirm that this 2 stage operation is, in fact, the way this is supposed to work?

**Comment by rjeffman** [comment]
@chsnell, the use of `action: member` requires that the sudocmdgroup exists, as it acts only on its members.

To create a sudocmdgroup, you have to have the sudocmds defined.

I'm not sure if I did it right to reproduce your steps, as I don't reproduce the issue here. The following playbook worked for me, and works in a single stage.

```yaml
---
- name: Playbook to ensure
  hosts: ipaserver

  vars:
    sudo_cmdgrps:
    - name: editors
      commands:
      - /bin/vi
    - name: networking
      commands:
      - /bin/ifconfig
      - /bin/wlist

  tasks:
    - name: Ensure sudocmds are present.
      ipasudocmd:
        ipaadmin_password: SomeADMINpassword
        name:
          - /bin/vi
          - /bin/ifconfig
          - /bin/wlist

    - name: Ensure sudo command groups are present
      ipasudocmdgroup:
        ipaadmin_password: SomeADMINpassword
        name: "{{ item.name }}"
        sudocmd: "{{ item.commands }}"
      loop: "{{ sudo_cmdgrps }}"
```

Note that I added the sudocmds explicitly, but this also works:

```yaml
---
- name: Playbook to ensure
  hosts: ipaserver

  vars:
    sudo_cmdgrps:
    - name: editors
      commands:
      - /bin/vi
    - name: networking
      commands:
      - /bin/ifconfig
      - /bin/wlist

  tasks:
    - name: Ensure sudocmds are present
      ipasudocmd:
        ipaadmin_password: SomeADMINpassword
        name: "{{ item.commands }}"
      loop: "{{ sudo_cmdgrps }}"

    - name: Ensure sudo command groups are present
      ipasudocmdgroup:
        ipaadmin_password: SomeADMINpassword
        name: "{{ item.name }}"
        sudocmd: "{{ item.commands }}"
      loop: "{{ sudo_cmdgrps }}"

```

**Comment by chsnell** [comment]
I'm sorry I wasn't clear initially.  The sudo commands themselves already exist, yes (created in a stanza prior to the ipasudocmdgroup one).  I had the logic the way you have it, and it did not actually add anything to the command groups, just created them.  We're running FreeIPA, version: 4.8.4 on RHEL 8.2 with version 0.2.0 of the ansible_freeipa collection under ansible 2.10.1:
```
# ansible --version
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
I'm going to update to the 0.2.1 collection version and see if that makes a difference.

**Comment by rjeffman** [comment]
@chsnell, it won't make a difference if you change to 0.2.1. I found the issue, and it is reproducible.

I'm marking this as a bug.

**Comment by chsnell** [comment]
Yeah, I'm noticing no change.  Glad you found it.  For anyone else that finds this before the PR is integrated, there is a workaround for this:  do 1 run of sudocmdgrp to add the groups then a 2nd stanza with action: member that will add the commands to the cmdgrp.

**Comment by rjeffman** [comment]
@chsnell, there is a PR (#445) to fix this issue.

It would be really nice if you could test it.

**Comment by chsnell** [comment]
> @chsnell, there is a PR (#445) to fix this issue.
> 
> It would be really nice if you could test it.

I tried yesterday, and don't think I got a good test as it didn't change the behavior.  Today has been fraught with issues at $WORK :/.

**Comment by rjeffman** [comment]
ansible-freeipa 0.3.0 has been released and has a fix for this issue.

If it does not work for you, please reopen this issue and let us know.

**Comment by chsnell** [comment]
Not sure how I can reopen this issue, but I tested this morning with the 0.3.0 release, and this is not resolved.  I get the same behavior as before.  I'm using this exact stanza:

`- name: Ensure sudo command groups are present
  ipasudocmdgroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ item.name }}"
    sudocmd: "{{ item.commands }}"
  loop: "{{ sudo_cmdgrps }}"
`
With a sample vars file like so:
`---
sudo_cmdgrps:
  -
    name: ALLBLUE
    commands:
      - /bin/su - db2inst1
      - /bin/vim /etc/nsswitch.conf
      - /bin/vim /etc/pam.d/db2`

**Comment by rjeffman** [comment]
@chsnell I just ran here, using 0.3.0 this playbook, created based on your input:
```yaml
---
- name: Test ipasudocmdgroup.
  hosts: ipaserver
  become: no
  gather_facts: no

  vars:
    ipaadmin_password: SomeADMINpassword
    sudo_cmdgrps:
      -
        name: ALLBLUE
        commands:
          - /bin/su - db2inst1
          - /bin/vim /etc/nsswitch.conf
          - /bin/vim /etc/pam.d/db2

  tasks:
    - name: Ensure sudocmds are present
      ipasudocmd:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.commands }}"
      loop: "{{ sudo_cmdgrps }}"

    - name: Ensure sudo command groups are present
      ipasudocmdgroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        sudocmd: "{{ item.commands }}"
      loop: "{{ sudo_cmdgrps }}"
```

And here is the result: 
```
[root@fed32 ~]# ipa sudocmdgroup-show allblue
  Sudo Command Group: allblue
  Member Sudo commands: /bin/su - db2inst1, /bin/vim /etc/nsswitch.conf, /bin/vim /etc/pam.d/db2
```

Prior to the playbook, there was no sudocmd or sudocmdgroup configured.

Can you provide the whole playbook, or the output of running the playbook with -vvv?
