### ISSUE TITLE
ipadnsrecord does not create A record and PTR with record_value and create_reverse

### ISSUE THREAD

**Issue by jonaz** [freeipa/ansible-freeipa#491]
```
- name: Add configured DNS records in IPA DNS
  freeipa.ansible_freeipa.ipadnsrecord:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "test"
    zone_name: "zone1.domain.com."
    record_type: "A"
    record_value: "10.10.10.10"
    create_reverse: yes
  become: True
```

This results in only PTR record created and no A record to `test.zone1.domain.com`

If i use the folloing instead both PTR and A records are created successfully. Should the above not work?

```
- name: Add configured DNS records in IPA DNS
  freeipa.ansible_freeipa.ipadnsrecord:
    ipaadmin_password: "{{ipaadmin_password}}"
    name: "test"
    zone_name: "zone1.domain.com."
    a_ip_address: "10.10.10.10"
    a_create_reverse: yes
  become: True
```
