### ISSUE TITLE
Weird error while calling ipaserver from a playbook

### ISSUE THREAD

**Issue by cjeanner** [freeipa/ansible-freeipa#50]
Hello,
I'm trying to integrate these roles in a global playbook, in order to get all the code in one place. In order to do so, I've added the requested entries in my ansible.cfg (see #11), created an "ipa" local role pointing to the right ipaserver/ipareplica depending on a host var. Overall, here's what my things look like:

inventory.yaml:
```YAML
all:
  hosts:
    master:
      ipa_master: yes
      other: variables
    replica1:
      ipa_master: no
....
```
roles/ipa/tasks/main.yaml
```YAML
- name: deploy ipaserver
  when: ipa_master|bool
  import_role:
    role: ipaserver
- name: deploy ip replica
  when: not ipa_master|bool
  import_role:
    role: ipareplica
```
playbook.yaml:
```YAML
- hosts: all
  roles:
    - common
    - ipa
```
In order to get a nice env, I've pushed a couple of variables in a local "env.yaml" file:
```YAML
ipaserver_domain: example.com
ipaserver_realm: EXAMPLE.COM
ipaserver_setup_dns: yes
```
In addition, ```ipaadmin_password``` and ```ipadm_password``` are in vault (dedicated file).

I then run the command:
```ansible-playbook playbook.yaml -e @vars.yaml -e @private-vars.yaml```
But it fails, saying ```ipaserver_test has no domain attribute```

What's wrong with my way of doing things? I would really love to NOT have hardcoded password nor information in the playbook and keep them in a var file - but I suspect this isn't possible due to the way the roles are done... ?

Any hint?

Cheers,

C.
