### ISSUE TITLE
ipadnsconfig buggy when forwarders partly exist

### ISSUE THREAD

**Issue by sluetze** [freeipa/ansible-freeipa#512]
Hi,

i've got a playbook that does my whole ipa-configuration.

There is a part where i set the dnsconfig with global forwarders
```yaml
    - name: Set dnsconfig.
      ipadnsconfig:
        state: present
        ipaadmin_password: "{{ ipaadmin_password }}"
        forwarders:
          - ip_address: 1.1.1.1
          - ip_address: 8.8.8.8
        forward_policy: only
        allow_sync_ptr: true
```
while debugging i manually modified the global forwarders and deleted one of them.

Now every run changes the forwarders!
if both are configured, no action is performed (Task: ok)
if both are not configured, both get configured (Task: changed)

if 1.1.1.1 is configured, it is deleted and 8.8.8.8 is set (Task: changed)
if 8.8.8.8 is configured, it is deleted and 1.1.1.1 is set (Task: changed)

I would expect the task to always set all forwarders, that are configured, or at least don't delete an configured one that is also included in the task.

-- sluetze
