### ISSUE TITLE
Deploy freeipa-client on Pop!_OS

### ISSUE THREAD

**Issue by gxe123** [freeipa/ansible-freeipa#523]
At present installing freeipa-client Pop!_OS not to recognise the distribution name and tries to use the ansible_freeipa/roles/ipaclient/vars/default.yml and the install fails.
Can I request support for deploying to the Ubuntu based Pop!_OS is supported.

As a workaround I suggest a simple fix would be the creation of a link 'Pop!_OS.yml' -> Ubuntu.yml.

**Comment by rjeffman** [comment]
@gxe123 thanks for the report, and for using ansible-freeipa in a different distro.

Adding support for every distro out there by adding new files to `roles/*/vars` is not a good option on the long run, and unfortunately, I don't have the best solution for this known problem (see #303).

What I'm proposing (PR #524) is to allow users to provide their own `vars` file, superseding the distro detection.

This are the variables someone might set, for the `ipabackup` module (RHEL values in the example):
```yaml
ipaserver_packages: [ "@idm:DL1/server" ]
ipaserver_packages_dns: [ "@idm:DL1/dns" ]
ipaserver_packages_adtrust: [ "@idm:DL1/adtrust" ]
ipaserver_packages_firewalld: [ "firewalld" ]
```
For `ipaserver` module, only `ipaserver_packages` is required, for `ipareplica` set `ipareplica_packages` and for `ipaclient` set `ipareplica_packages`.

Hope this helps.
