### ISSUE TITLE
Simple module error for ipaclient_test

### ISSUE THREAD

**Issue by TheRedGreek** [freeipa/ansible-freeipa#527]
In order for all the examples to work, a default value should be set for the kinit_admin variable. Without the default value, or the user adding a value for the kinit_attemps option, the module will error out.

[https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaclient/library/ipaclient_test.py#L277](url)

**Comment by rjeffman** [comment]
Which example fail to work? What was the error?

**Comment by TheRedGreek** [comment]
```
- hosts: localhost
  gather_facts: false
  tasks:
  - ipaclient_test:
    register: test
```
Here is the error: 

[https://github.com/freeipa/ansible-freeipa/blob/3c666ccdaaddd62ec0c6e8788602ee0c100349cf/roles/ipaclient/library/ipaclient_test.py#L347](url)
