### ISSUE TITLE
Can't create a privilege with permissions.

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#529]
When creating a `privilege` that contain permissions, as in:
```yaml
- name: Create privilege
  ipaprivilege:
    name: MyPrivilege
    permission:
    - "MyPermission"
```

If the `privilege` does not previously exists, the task fails with:

```
TASK [Create privilege] ********************************************************
fatal: [rhel84.ipa.test]: FAILED! => {"changed": false, "msg": "argument of type 'NoneType' is not iterable"}
```

The problem happens in `compare_args_ipa()` on `plugins/module_utils/ansible_freeipa_module.py` (in line 285, on commit b598470):
```python
for key in args.keys():
        if key not in ipa:
            module.debug(
```

The fix should be on `ansible_freeipa_module.py`, as the arguments are not tested against None, and it might happen again, in other modules that use this function passing `None` as arguments to this function.
