### ISSUE TITLE
User password reset playbook

### ISSUE THREAD

**Issue by c5234416** [freeipa/ansible-freeipa#537]
Could you please create a playbook for user password reset?

**Comment by t-woerner** [comment]
Ensuring a user with a new password is a subset of "Example playbook to ensure a user is present" in https://github.com/freeipa/ansible-freeipa/blob/master/README-user.md#usage

```
  - name: Ensure user pinky is present 
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: pinky
      password: "no-brain"
```
