### ISSUE TITLE
Unclear NTP related settings for ipaclient

### ISSUE THREAD

**Issue by dawud** [freeipa/ansible-freeipa#55]
As of now, there are two NTP related settings in the [defaults for the `ipaclient` role](https://github.com/freeipa/ansible-freeipa/blob/a28378396f2c34af336fd86bd4b081391d1b6ff6/roles/ipaclient/defaults/main.yml), namely:

```yml
ipaclient_ntp: no
ipaclient_no_ntp: no
```

Only the latter is documented:

> The ipaclient_no_ntp bool value defines if NTP will not be configured and enabled. ipaclient_no_ntp defaults to no.

Checking where these settings are used in the tasks file, it can be seen they are parameters of the `ipadiscovery` and `ipaextras` modules, where the relevant options are documented as follows:

```yaml
---                                                                                                                                                                                                                                                                                                                      
module: ipadiscovery  
  no_ntp:                                                                                                                                                                                                                                                                                                                
    description: Do not sync time and do not detect time servers                                                                                                                                                                                                                                                         
    required: false                                                                                                                                                                                                                                                                                                      
    default: false                                                                                                                                                                                                                                                                                                       
    type: bool                                                                                                                                                                                                                                                                                                           
    default: no 
```
and

```yaml
---                                                                                                                                                                                                                                                                                                                      
module: ipaextras  
  ntp:                                                                                                                                                                                                                                                                                                                   
    description: Set to no to not configure and enable NTP                                                                                                                                                                                                                                                               
    required: false                                                                                                                                                                                                                                                                                                      
    type: bool                                                                                                                                                                                                                                                                                                           
    default: no
```

It is a bit confusing (at least for me) what each one accomplishes, if they do the same, i.e. configure the NTP service for the client
If they don't, `ipaclient_ntp` is missing from the docs.

The `ipa-client-install` CLI utility only has one of the options:

>     -N, --no-ntp        do not configure ntp
