### ISSUE TITLE
Dns entry should remove the segment of the zone

### ISSUE THREAD

**Issue by Tcharl** [freeipa/ansible-freeipa#551]
I tried to add a dns entry for each of my clients like like
```
- name: ansible-nameserver | ipa_dns_client | ensure reverse zone is created
  shell: |
    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
    echo '{{ (current_client_ip.msg | ipsubnet(16) | ansible.netcommon.ipaddr('revdns')) | replace('0.0','') }}' | ipa dnszone-add --name-from-ip={{ current_client_ip.msg | ipsubnet(16) }}
  no_log: True
  failed_when: False
  delegate_to: "{{ groups[idm_group][0] }}"
  changed_when: False
  become: true

- name: ansible-nameserver | ipa_dns_client | ensure dns entry is created
  freeipa.ansible_freeipa.ipadnsrecord:
    ipaadmin_password: "{{ company_realm_password }}"
    zone_name: "{{ company_domain }}"
    name: "{{ (hostname | default(machine_hostname.stdout)) | replace(company_domain, '') }}"
    a_ip_address: "{{ current_client_ip.msg }}"
    a_create_reverse: yes
    state: present
  delegate_to: "{{ groups[idm_group][0] }}"
```

However, this one fails badly because freeipa tells me that the 'name' is not among the managed zone
```
fatal: [master.internal.osgiliath.net -> idm.internal.osgiliath.net]: FAILED! => {"changed": false, "msg": "dnsrecord_add: internal.osgiliath.net: invalid 'idnsname': out-of-zone data: record name must be a subdomain of the zone or a relative name"}
```

on the opposite, if I remove the `| replace(company_domain, '')` instruction, it does not fail anymore, but create a dns with doubled (dn.tld)...

How can I circumvent that?

**Comment by rjeffman** [comment]
I'm fishing a little bit here, as it might look a problem with data, which I don't have access.

It looks like the resulting `name` is ending with a dot (`.`), meaning it is an absolute name, instead of a relative one.

This is what I think might reproduce what you are seeing.

Playbook: 
```yaml
---
- name: Reproduce dnsrecord failure.
  hosts: ipaserver
  gather_facts: yes
  become: yes

  tasks:
  - ipadnsrecord:
      ipaadmin_password: SomeADMINpassword
      zone_name: ipa.local
      name: "{{ item['host'] | replace(item['zone'], '') }}"
      a_ip_address: "{{ item['ip'] }}"
    with_items:
      - {'host': "h1.ipa.local", 'zone': ".ipa.local", 'ip': "192.168.122.123"}
      - {'host':"h2.ipa.local", 'zone':"ipa.local", 'ip':"192.168.122.124"}
...
```

Output:

```
[rjeffman@dantooine ansible-freeipa]$ ansible-playbook -i inventory reproducer.yml 

PLAY [Reproduce dnsrecord failure.] ****************************************************************

TASK [Gathering Facts] *****************************************************************************
ok: [cos83.ipa.local]

TASK [ipadnsrecord] ********************************************************************************
changed: [cos83.ipa.local] => (item={'host': 'h1.ipa.local', 'zone': '.ipa.local', 'ip': '192.168.122.123'})
failed: [cos83.ipa.local] (item={'host': 'h2.ipa.local', 'zone': 'ipa.local', 'ip': '192.168.122.124'}) => {"ansible_loop_var": "item", "changed": false, "item": {"host": "h2.ipa.local", "ip": "192.168.122.124", "zone": "ipa.local"}, "msg": "dnsrecord_add: ipa.local: invalid 'idnsname': out-of-zone data: record name must be a subdomain of the zone or a relative name"}

PLAY RECAP *****************************************************************************************
cos83.ipa.local            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

Note the one of the `zone` (which would be your `company_domain`) starts with a `.` and the other one doesn't. The one without the `.` leaves a trailing dot in the hostame, making it an absolute name, so the error.
