### ISSUE TITLE
ipasudorule removes hosts/groups if they are not lowercase

### ISSUE THREAD

**Issue by sluetze** [freeipa/ansible-freeipa#589]
## symptom
when having a non-normalized list of hosts which include upper and lowercase the hosts and groups are added to the rule in first  run and removed in the second. in the third run they get added again.

## Situation
I have a list of groups, which is used to create usergroups and hostgroups. I also use this list to create sudorules and automember rules. The list is written in upper and lowercase.

## code
```yaml
  vars:
    groups_present:
      - element1
      - Element2
      - eLeMenT3
      - ELEMENT4
  tasks:
    - name: 'Ensure sudo-Rule for each group'
      ipasudorule:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: 'default_{{ groupname }}'
        state: present
        description: 'Default rule to allow Group {{ groupname }} sudo-access to their servers'
        cmdcategory: all
        hostgroup: "{{ groupname  }}"
        group: "{{ groupname }}"
      loop: '{{ groups_present }}'
      loop_control:
        label: "{{ groupname }}"
        loop_var: groupname
```

## the problem
the problem seems to be, that IPA internally creates hostgroups and usergroups as lowercase instances. which makes totally sense. When adding a hostgroup or group IPA normalizes the string and sets it to a lowercase string.
In subsequent runs, when the list of existing and supplied hosts are evaluated, the evaluation sees the lowercase and the non-lowercase elements as different. Since deletion is done after addition, the hostgroup / group gets removed.

## the fix
I guess it would be easiest to just normalize the params when they are incoming:
https://github.com/freeipa/ansible-freeipa/blob/c75b0292a100081df94a27cceecfee4412946759/plugins/modules/ipasudorule.py#L307-L310

## the workaround
```yaml
    - name: 'Ensure sudo-Rule for each group'
      ipasudorule:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: 'default_{{ groupname }}'
        state: present
        description: 'Default rule to allow Group {{ groupname }} sudo-access to their servers'
        cmdcategory: all
        hostgroup: "{{ groupname | lower }}"
        group: "{{ groupname | lower }}"
      loop: '{{ groups_present }}'
      loop_control:
        label: "{{ groupname }}"
        loop_var: groupname
```

## Version
ansible==4.2.0
ansible-core==2.11.2
freeipa.ansible_freeipa 0.3.6
