### ISSUE TITLE
sudorule_add_runasuser not idempotent 

### ISSUE THREAD

**Issue by 2342435** [freeipa/ansible-freeipa#664]
Hello,

```
- name: sudo user1 on host1
  ipasudorule:
    ipaadmin_password: "{{ vault_ipa_admin_password }}"
    name: sudo_user1_host1_nopasswd_apache
    cmdcategory: all
    description: Allow user1 to run every command as apache with sudo without password
    host: user1.domain.com
    runasuser: apache
    sudooption:
    - '!authenticate'
    user: user1
  run_once: true

```
will work once, not twice. apache is an external/local user. However it seems to be the same with IPA users.

Appreciate your help! Thanks!

Regards

Sören
