### ISSUE TITLE
ipahostgroup not idempotent and with error

### ISSUE THREAD

**Issue by 2342435** [freeipa/ansible-freeipa#666]
Hi,

with this playbook i autocreate my ipahostgroups from our ansible inventory.

```
- name: Autocreation of hostgroups from inventory
  ipahostgroup:
    ipaadmin_password: "{{ vault_ipa_admin_password }}"
    name: "{{ item.key }}"
    state: present
    host: "{{ item.value }}"
  when:
    - 'item.key is not match("test*")'
    - 'item.key is not match("all")'
  loop: "{{ lookup('dict', groups) }}"
  run_once: true
  ignore_errors: yes

```

I fetch ansible-freeipa via ansible-galaxy.
In the current version 0.4.2 on first run the host-groups are filled, after second run they are empty, third run filled, ...
My colleague has an older version of the collection with a timestamp of the files from 30.09.2021, there it worked.

Thank you very much!

Regards

Sören
