### ISSUE TITLE
sudorule: Host member shortname vs. fqdn error.

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#672]
Giver a fresh instalation of FreeIPA, and the tasks:
```yaml
    - name: Add hosts
      ipahost:
        ipaadmin_password: SomeADMINpassword
        name: host01.ipa.test
        force: yes

    - name: Add test sudo rule
      ipasudorule:
        ipaadmin_password: SomeADMINpassword
        name: sudorule_for_hosts
    
    - name: Manage sudorule host member
      ipasudorule:
        ipaadmin_password: SomeADMINpassword
        name: sudorule_for_hosts
        host: "{{ item }}"
        action: member
      with_items: "{{ hosts }}"
```

Tasks will properly execute when `hosts` is defined as:
```yaml
vars:
    hosts:
      - host01
      - host01.ipa.test
```

But if we swap the hostname order:
```yaml
vars:
    hosts:
      - host01.ipa.test
      - host01
```

Running tasks result in a failure for the second hostname:
```
TASK [Manage sudorule host member] ********************************************************
changed: [rhelx.ipa.test] => (item=host01.ipa.test)
failed: [rhelx.ipa.test] (item=host01) => {"ansible_loop_var": "item", "changed": false, "item": "host01", "msg": "sudorule_add_host: host host01.ipa.test: This entry is already a member"}
```

P.S.: As a workaround, avoid short names for hostnames and use only FQDN.
