### ISSUE TITLE
task need 10x time when using become: true

### ISSUE THREAD

**Issue by sluetze** [freeipa/ansible-freeipa#678]
# Problem:
when using `become: true` in a task or playbook, the execution slows down.

# Information:
I had a playbook which configured the full ipaserver and created users. it was terrible slow and took hours. i began to split it into smaller tasks, to get a better grasp of why it was slow. I'm executing the tasks on the ipaserver.

I found, that tasks which run with `become: true` take 45 seconds per item, while tasks without `become:true` run in 3 seconds per item (which is not fast, but ok).

I also found, that while executing the task, on the ipaserver the process `sssd_kcm` process takes the complete cpu and errors out after some time.

the log of sssd_kcm states
```
(2021-11-04 14:38:30): [kcm] [sec_get] (0x0040): Cannot retrieve the secret [2]: No such file or directory
   *  (2021-11-04 14:38:30): [kcm] [kcm_cmd_done] (0x0400): KCM operation GET_CRED_BY_UUID returned [0]: Success
   *  (2021-11-04 14:38:30): [kcm] [kcm_send_reply] (0x2000): Sending a reply
   *  (2021-11-04 14:38:30): [kcm] [kcm_output_construct] (0x1000): Sending a reply with 161 bytes of payload
   *  (2021-11-04 14:38:30): [kcm] [queue_removal_cb] (0x0200): Removed queue for 0 
   *  (2021-11-04 14:38:30): [kcm] [kcm_send] (0x2000): All data sent!
   *  (2021-11-04 14:38:30): [kcm] [kcm_input_parse] (0x1000): Received message with length 22
   *  (2021-11-04 14:38:30): [kcm] [kcm_get_opt] (0x2000): The client requested operation 10
   *  (2021-11-04 14:38:30): [kcm] [kcm_cmd_send] (0x0400): KCM operation GET_CRED_BY_UUID
   *  (2021-11-04 14:38:30): [kcm] [kcm_cmd_send] (0x1000): 18 bytes on KCM input
   *  (2021-11-04 14:38:30): [kcm] [kcm_op_queue_send] (0x0200): Adding request by 0 to the wait queue
   *  (2021-11-04 14:38:30): [kcm] [kcm_op_queue_get] (0x1000): No existing queue for this ID
   *  (2021-11-04 14:38:30): [kcm] [kcm_op_queue_send] (0x1000): Queue was empty, running the request immediately
   *  (2021-11-04 14:38:30): [kcm] [kcm_cmd_done] (0x0400): KCM operation GET_CRED_BY_UUID returned [0]: Success
   *  (2021-11-04 14:38:30): [kcm] [kcm_send_reply] (0x2000): Sending a reply
   *  (2021-11-04 14:38:30): [kcm] [kcm_output_construct] (0x1000): Sending a reply with 161 bytes of payload
   *  (2021-11-04 14:38:30): [kcm] [queue_removal_cb] (0x0200): Removed queue for 0 
   *  (2021-11-04 14:38:30): [kcm] [kcm_send] (0x2000): All data sent!
[...]
   *  (2021-11-04 14:38:30): [kcm] [sss_sec_get] (0x0400): Retrieving a secret from [persistent/0/default]
   *  (2021-11-04 14:38:30): [kcm] [sss_sec_get] (0x2000): Searching for [(|(type=simple)(type=binary))] at [cn=default,cn=0,cn=persistent,cn=kcm] with scope=base
   *  (2021-11-04 14:38:30): [kcm] [sss_sec_get] (0x1000): No secret found
   *  (2021-11-04 14:38:30): [kcm] [sec_get] (0x0040): Cannot retrieve the secret [2]: No such file or directory
``` 
per command it's a whopping 1075 lines of the same cutout i pasted.

since sssd_kcm has something to do with caches, i also tried to use ipaapi_ldap_cache no, which did not help at all.

# Example Playbook
```yaml
  tasks:
    - name: Ensure Serviceaccounts in IPA in snail speed
      become: true
      ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        first: "{{ item.first }}"
        last: "serviceaccount"
        shell: /sbin/nologin
        password: "{{ item.password }}"
        state: present
        update_password: always
      loop: "{{ serviceaccounts_present }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Ensure Serviceaccounts in IPA in normal speed
      ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        first: "{{ item.first }}"
        last: "serviceaccount"
        shell: /sbin/nologin
        password: "{{ item.password }}"
        state: present
        update_password: always
      loop: "{{ serviceaccounts_present }}"
      loop_control:
        label: "{{ item.name }}"
```

# Versions
freeipa.ansible_freeipa 0.4.2  (same problem with 0.3.8)

freeipa-client-common-4.9.6-1.fc33.noarch
libipa_hbac-2.5.1-2.fc33.x86_64
sssd-ipa-2.5.1-2.fc33.x86_64
freeipa-healthcheck-core-0.9-2.fc33.noarch
python3-libipa_hbac-2.5.1-2.fc33.x86_64
freeipa-server-common-4.9.6-1.fc33.noarch
freeipa-selinux-4.9.6-1.fc33.noarch
freeipa-common-4.9.6-1.fc33.noarch
python3-ipalib-4.9.6-1.fc33.noarch
python3-ipaclient-4.9.6-1.fc33.noarch
freeipa-client-4.9.6-1.fc33.x86_64
python3-ipaserver-4.9.6-1.fc33.noarch
freeipa-server-4.9.6-1.fc33.x86_64
freeipa-server-dns-4.9.6-1.fc33.noarch
