### ISSUE TITLE
ipavault not idempotent.

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#680]
If running the same task to ensure an ipavault is present, while adding members at the same time, the task is not idempotent.

If the following task is executed twice, it will return `changed: true` on both executions:

```yaml 
- name: Ensure vault is present with members.
  ipavault:
    ipaadmin_password: SomeADMINpassword
    name: "{{ vault.name }}"
    vault_type: "{{ vault.vault_type }}"
    users:
      - user02
    groups:
      - vaultgroup
    owners:
      - user03
    ownergroups:
      - vaultgroup
```
