### ISSUE TITLE
ipagroup can't handle mixed lists of users

### ISSUE THREAD

**Issue by sluetze** [freeipa/ansible-freeipa#707]
ipagroup seems to have a problem when using a list of users with 'member'

given the following task:
```yaml
    - name: 'Add admins to admin group'
      ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: admins
        action: member
        user: '{{ admins_present }}'
```

and a var like this:
```yaml
admins_present:
  - admin1
  - admin2
  - admin3
```

when an (existing) user (`admin4`) is added to the list, the task fails

```bash
TASK [Add admins to admin group] ************************************************************************************************************************************************************
Dienstag 14 Dezember 2021  10:12:44 +0100 (0:00:03.003)       0:00:07.383 ***** 
fatal: [ipaserver.domain.tld]: FAILED! => {"changed": false, "msg": "group_add_member: user admin1: This entry is already a member, group_add_member: user admin2: This entry is already a member, group_add_member: user admin3: This entry is already a member"}
```

but the missing user is added to the group, thus subsequent runs succeed with `ok` state.

The module should show changed and just add the user. the failed-state seems to be a false positive.

It's possible to work arround this with a loop, but this has a performance hit.

**Comment by rjeffman** [comment]
Thank you for reporting this issue.

I can reproduce it, and it is something that was already on my "TODO list".

**Comment by p-tselios** [comment]
I experience the same issue with external members. 
When you add the users in the 1st run everything is OK and the task reports "changed" as it should. However, if you add external users the 2nd run fails: 

Example group definition:

```
  - name: WSGroup02
    description: "An external group"
    gid: 120000
    external: true
    externalmember:
      - 'EXAMPLE.NET\aduser01'
      - 'EXAMPLE.NET\aduser02'
```

Playbook fails with this error message:

```
failed: [idm.lab.example.net] (item=WSGroup02 - present) => {"ansible_loop_var": "item", "changed": false, "item": {"description": "An external group", "external": true, "externalmember": ["EXAMPLE.NET\\aduser01", "EXAMPLE.NET\\aduser02"], "name": "WSGroup02"}, "msg": "group_add_member: group S-1-5-21-3950909341-3028684245-1018452525-1103: This entry is already a member, group_add_member: group S-1-5-21-3950909341-3028684245-1018452525-1104: This entry is already a member"}
```

The module should handle this with OK.
