### ISSUE TITLE
ipauser fails with "The password is not set"

### ISSUE THREAD

**Issue by ikke-t** [freeipa/ansible-freeipa#730]
When I try running the playbook after a user is already once created (re-running), the ipauser tasks always fails with

```
TASK [Create users] ********************************************************************************************************************************
Friday 14 January 2022  13:37:52 +0200 (0:00:02.096)       0:00:02.139 ******** 
fatal: [rh-idm-01.cool.lab]: FAILED! => {"changed": false, "msg": "The password is not set"}
```

This is the task:
```
    - name: Create users
      freeipa.ansible_freeipa.ipauser:
        state: present
        update_password: on_create
        users:
          - name: ikke
            first: Ilkka
            last: Tengvall
            uid: 10001
            gid: 10001
            password: "coolpw-changeme123"
            # passwordexpiration: "2025-12-31 23:59:59"
            # yamllint disable-line rule:line-length
            sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC577GzJaVha0u0byNEFLDbGQhMkPSyXeT9gqIfZMKIxgh9PhOjpHl739lcdbsbgiUVAjZYI7M3PwuGghYTZpk2amJEZXUrul2MQudEc5tUX9wbpdKx9PEhzCywynRN+ZWGK15R5uVyc8mhqbvE0xQnkX0d+/eh+K8reFw451rPJuXrbbk13x/KBs/WqjEGCe6Yto/BotRRadpxTP5gPTxs/MIZ9LZC5EjmuOxDVt1xNROUNdD7gdK8DdpAHK72OoaT5ooc3Zq9uum4sYhCc611IGMNy2yjaYsJWWiVpDFy+APs5u9oK7wdtYFZwhf6B1O3U1X21CoaU8nJsFxJmI1g32IaAfh18sGiTBKKu8vYfF1y2eHa0I/App5WI+H5BS9WV7QyW5s7FQQ9R0okZ3kWbiGj8tVcVdTviwKmNm/7FtED6vPDe9ji+ou56YyzX7sd8ZFZjCX4rG9ZfpCzwsCCRdYHcKEyTIM5is9aggSUVWIkhdD9IKKsJEuW2ZCo8zpVMqSKm4G05tieIAGGr546m1OiTVBFVzuhYuTmwGuVfR0szoDCV6nOc1vcZMLyWYM5zWZRMuCw6NMzMuL+ot0JXyVKtgfFt4q5Q+Ha87jYXsiLOezsTiycgG1c/HmF4NxfWHt8nkDP/hQI0ESb1AKqxqp3++mCciHd1PlE/Y1CaQ==

```

Why can't I rerun it?
