### ISSUE TITLE
ipauser: Failed to add user with expired principal.

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#740]
When creating a new user with an expired principal, the user is added in executed in `server` context, but fails if executed on `client` context.

```yaml
- name: User pinky present
    ipauser:
      ipaadmin_password: SomeADMINpassword
      ipaapi_context: "client"
      name: pinky
      principalexpiration: "20220119235959"
      first: pinky
      last: acme
```

Observed output:
```
TASK [User pinky present] *******************************************************************
fatal: [fedcli.ipa.test]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "user_add: pinky: Constraint violation: Account expired"}
```

Software versions:

ansible-freeipa version: 1.5.3
ansible-core: 2.11.6
target hosts: Fedora 35
FreeIPA: :4.9.8
