### ISSUE TITLE
[RFE] ipauser should ignore unecessary variables when state != present

### ISSUE THREAD

**Issue by itcultus** [freeipa/ansible-freeipa#746]
If I want to keep in my inventory a single user list on which I simply specify all user arguments and (optionally) the state, then I have to user some really ugly code like the following: 

```yaml
- name: Manage users
  freeipa.ansible_freeipa.ipauser:
    ipaadmin_password: "{{ admin_password }}"
    name: "{{ item.name }}"
    first: "{{ item.first if item.state | default('present') == 'present' else omit }}"
    last: "{{ item.last if item.state | default('present') == 'present' else omit }}"
    uid: "{{ item.uid if item.state | default('present') == 'present' else omit }}"
    gid: "{{ item.uid if item.state | default('present') == 'present' else omit }}"
    state: "{{ item.state | default('present') }}"
    loginshell: "{{ item.loginshell | default('/bin/bash') if item.state | default('present') == 'present' else omit }}"
    homedir: "{{ item.homedir | default('/home/' + item.name) if item.state | default('present') == 'present' else omit }}"
    email: "{{ item.email | default(omit) if item.state | default('present') == 'present' else omit  }}"
    sshpubkey: "{{ item.ssh_key_pub_list | default(omit) }}"
    password: "{{ item.password | default('changeme') if item.state | default('present') == 'present' else omit }}"
    update_password: "{{ 'on_create' if item.state | default('present') == 'present' else omit }}"
  loop: "{{ global_user_list }}"
```
Personally, I don't see the point of having different lists of users based on their state, and definitely I would prefer to transfer the "logic" inside the module and not in the inventory/variables.
