### ISSUE TITLE
ipauser is not idempotent on preserved users

### ISSUE THREAD

**Issue by itcultus** [freeipa/ansible-freeipa#747]
I believe this is a bug. 
My current user list is: 

```yaml
user_list:
  - name: C00001114
    uid: 30004
    first: One
    last: More
    password: 'changeme'
    state: absent
    preserve: true
    sshpubkey:
      - 'ssh-rsa ...'
```

The user is correctly moved to the "Preserved" user list in IPA/IdM. However, when I re-run the playbook, I get this error: 

```
msg: 'user_del: C00001114: c00001114: user is already preserved'
```
