### ISSUE TITLE
is it possible to use the ipaclient role without defined inventory groups?

### ISSUE THREAD

**Issue by jlozadad** [freeipa/ansible-freeipa#78]
or will this require significant changes on the tasks themselves? the reason I'm asking is because a lot of hosts are going to be registered after being provisioned and use another play to configure them that includes this role. They are other workaround like using add_host again to create the proper groups but, that can be dirty.

**Comment by t-woerner** [comment]
The ipareplica role is using the ipaclient role this way:

```
  - name: Install - Setup client
    include_role:
      name: ipaclient
    vars:
      state: present
      ipaclient_domain: "{{ result_ipareplica_test.domain | default(omit) }}"
      ipaclient_realm: "{{ result_ipareplica_test.realm | default(omit) }}"
      ipaclient_servers: "{{ ipareplica_servers | default(omit) }}"
      ipaclient_hostname: "{{ result_ipareplica_test.hostname }}"
      ipaclient_no_ntp: "{{ result_ipareplica_test.ipa_python_version
                            < 40690 }}"
      ipaclient_install_packages: "{{ ipareplica_install_packages }}"
    when: not result_ipareplica_test.client_enrolled
```
Something like this should also work for you.
