### ISSUE TITLE
README-group.md group name correction

### ISSUE THREAD

**Issue by maroskukan** [freeipa/ansible-freeipa#790]
Hello,

The following code snipped in `README-group.md`:

```yml
---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  # Add group members sysops and appops to group sysops
  - ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: ops
      group:
      - sysops
      - appops
```

Should read:

```yml
---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  # Add group members sysops and appops to group ops
  - ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: ops
      group:
      - sysops
      - appops
```

Also a quick question, when I remove a group, for example the `sysops`, do I need to also remove its membership in `ops` group?
