### ISSUE TITLE
Ensure that IPA server packages are installed: /usr/bin/python2.7: not found

### ISSUE THREAD

**Issue by patsevanton** [freeipa/ansible-freeipa#796]
Hello! Thanks for role freeipa!
I try install and get error
```
/usr/bin/python2.7: not found
```

is python3 support planned ?

Playbook
```
---
- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  collections:
    - freeipa.ansible_freeipa
  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present
```

Inventory
```
all:
  children:
    ipaserver:
      hosts:
        "freeipa":
          ansible_host: "xxxxx"
  vars:
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
```

Ansible output
```
TASK [freeipa.ansible_freeipa.ipaserver : Install - Ensure that IPA server packages are installed] *************************************************************************************
Wednesday 06 April 2022  15:04:32 +0600 (0:00:00.048)       0:00:03.311 *******
fatal: [freeipa]: FAILED! => changed=false
  module_stderr: |-
    Shared connection to 51.250.102.227 closed.
  module_stdout: |-
    /bin/sh: 1: /usr/bin/python2.7: not found
  msg: |-
    The module failed to execute correctly, you probably need to set the interpreter.
    See stdout/stderr for the exact error
  rc: 127
```

Environment

Version
```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

Server where ansible
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

Remote server
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
```
