### ISSUE TITLE
How to skip hostname setup

### ISSUE THREAD

**Issue by bioinfornatics** [freeipa/ansible-freeipa#816]
Dear,

I have to skip the hostname setup as I use podman/rootless container. 
So it is not allowed to change the container hostname in this case.

I take a look to the code and they maybe a little gap by the use of `_hostname_overridden`
Indeed it seems that I could skip this step if the variable is set to false.

We can see at [install.yml line 194](https://github.com/freeipa/ansible-freeipa/blob/b598470c2bba5e7cb0792074792e1aa5ff67f6fa/roles/ipaserver/tasks/install.yml#L194)   that the variable take the value from `result_ipaserver_test` object.
The object  `result_ipaserver_test` is define between [line 60](https://github.com/freeipa/ansible-freeipa/blob/b598470c2bba5e7cb0792074792e1aa5ff67f6fa/roles/ipaserver/tasks/install.yml#L6 ) and [line 128](https://github.com/freeipa/ansible-freeipa/blob/b598470c2bba5e7cb0792074792e1aa5ff67f6fa/roles/ipaserver/tasks/install.yml#L128) but the key `_hostname_overridden` is not set.

then it is impossible to not ovveride hostname

my goal is to avaoid the call `['hostnamectl', 'set-hostname', hostname]`.
as Example I have a `molecule.yml`

```yml
---
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ipa
#    image: quay.io/freeipa/freeipa-server:rocky-8-4.9.6
    image: quay.io/rockylinux/rockylinux
    pre_build_image: true
    privileged: false
    network: org_ipa
    subnet: 10.0.1.0/16
    ip: 10.0.1.1
    hostname: ipa.org.test
    exposed_ports:
# TODO: net.ipv4.ip_unprivileged_port_start=53 ...
#      - '53'
#      - '80'
#      - '88'
#      - '123'
#      - '389'
#      - '464'
#      - '636'
      - '8080'
      - '8443'
      - '9180'
      - '9443'
      - '9444'
      - '9445'
      - '9446'
      - '9701'
      - '7389'
    published_ports:
# TODO: net.ipv4.ip_unprivileged_port_start=53 ...
#      - '53:53'
#      - '80:80'
#      - '88:88'
#      - '123:123'
#      - '389:389'
#      - '464:464'
#      - '636:636'
      - '8080:8080'
      - '8443:8443'
      - '9180:9180'
      - '9443:9443'
      - '9444:9444'
      - '9445:9445'
      - '9446:9446'
      - '9701:9701'
      - '7389:7389'
    etc_hosts:
      ipa.org.test: 10.0.1.1
    systemd: 'always'
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - all
      - ipa_server

  - name: client1
    image: quay.io/rockylinux/rockylinux
    pre_build_image: true
    privileged: false
    network: org_ipa
    subnet: 10.0.1.0/16
    ip: 10.0.1.2
    hostname: client1.org.test
    etc_hosts:
      client1.org.test: 10.0.1.2
    systemd: 'always'
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - all
      - client
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ipaadmin_password: 'TodoSetPassword'
        ipa_domain: 'org.test'
        ipa_realm: 'ORG.TEST'
      ipa_server:
        ipadm_password: 'TodoSetPassword'
        is_ipa_replica: False
        ipaserver_setup_dns: True
        ipaserver_setup_kra: True
        ipaserver_auto_forwarders: True
        ipaserver_no_dnssec_validation: True
        ipaserver_auto_reverse: True
        ipaserver_domain: ipa.org.test
        ipaserver_realm: 'ORG.TEST'
        ipaserver_hostname: 'ipa.org.test'
        result_ipaserver_test:
          _hostname_overridden: False

    host_vars:
      ipa:
        inventory_ip: 10.0.1.1
      client1:
        inventory_ip: 10.0.1.2
verifier:
  name: ansible
```

and `prepare.yml`

```yml
---
- name: Prepare
  hosts: ipa_server
  gather_facts: false
  tasks:
   - name: Include ipaserver role
    include_role:
      name: freeipa.ansible_freeipa.ipaserver
```
