### ISSUE TITLE
ipauser state:present is re-enabling disabled users

### ISSUE THREAD

**Issue by tfmm** [freeipa/ansible-freeipa#858]
I have a process outside of Ansible that checks for inactive users and disables them automatically, however, when my playbook is run which uses ipauser to create the users, it sets them to enabled instead of just leaving them alone. 

Am I missing an option or is there another state I can use in the playbook that won't update the users from disabled to enabled? 

User creation example:
```
- name: users - create users loop
  ipauser:
    name: TestUser
    givenname: Test
    sn: User
    password: examplePass
    mail:
    - testuser@example.com
    update_password: on_create
    state: present
```

**Comment by t-woerner** [comment]
Which ansible-freeipa version are you using?

I tried to replicate your issue with version 1.8.2 and also older versions, but `state: present` is not touching the disabled state with `nsaccountlock` of a user.

```
  - name: users - create users loop
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: TestUser
      givenname: Test
      sn: User
      password: examplePass
      email:
      - testuser@example.com
      update_password: on_create
      state: present

  - name: Ensure TestUser is disabled
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: TestUser
      state: disabled

  - name: users - create users loop
    ipauser:
      ipaadmin_password: SomeADMINpassword
      name: TestUser
      givenname: Test
      sn: User
      password: examplePass
      email:
      - testuser@example.com
      update_password: on_create
      state: present
```

This is resulting in the log

```
TASK [users - create users loop] ***********************************************
changed: [ipaserver.example.test] => {"changed": true, "user": {}}

TASK [Ensure TestUser is disabled] *********************************************
changed: [ipaserver.example.test] => {"changed": true, "user": {}}

TASK [users - create users loop] ***********************************************
ok: [ipaserver.example.test] => {"changed": false, "user": {}}
```

Using the command line afterwards shows that the user is disabled:

```
$ ipa user-show TestUser | grep disabled
  Account disabled: True
$ ipa user-disable TestUser
ipa: ERROR: This entry is already disabled
```

BTW: The option `mail` is not supported by the ipauser module in ansible-freeipa.
