### ISSUE TITLE
ipadnsconfig no longer idempotent

### ISSUE THREAD

**Issue by scaronni** [freeipa/ansible-freeipa#862]
Just upgraded the collection from 0.4.2 to 1.8.1. This task is no longer idempotent:
```
- name: Set FreeIPA global DNS configuration
  delegate_to: localhost
  become: False
  run_once: True
  freeipa.ansible_freeipa.ipadnsconfig:
    ipaadmin_principal: "{{ lookup('env', 'USER') }}"
    forwarders:
      - ip_address: 10.90.2.93
      - ip_address: 10.90.2.94
    forward_policy: only
    allow_sync_ptr: true
```
On 0.4.2 it was working fine and not returning a change if there was no actual change, now it just barfs out with:
```
fatal: [ipa.example.com -> localhost]: FAILED! => changed=false 
  msg: 'dnsconfig_mod: no modifications to be performed'
```
