### ISSUE TITLE
setting parent for a group reports changed when it should not:

### ISSUE THREAD

**Issue by donescup** [freeipa/ansible-freeipa#868]
There are issues with setting the parent of a group:
(1) setting the parent twice, leads to changed in the second time; but not in all cases.
(2) running the playbook with check mode still reports changed; this seems to work fine for some (reports OK), for others it shows changed.

Playbook:
```yaml
- name: Create ipa group {{ group.name }}
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ ipaadmin_pass }}"
    name: "{{ group.name }}"
    gidnumber: "{{ group.gid }}"
  loop:
    - name: parent
      gid: 9991
    - name: child1
      gid: 9992
    - name: child2
      gid: 9993
  loop_control:
    loop_var: group

- name: Set parent parent for group {{ item }}
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ ipaadmin_pass }}"
    name: parent
    group: "{{ item }}"
  loop:
    - child1
    - child2

- name: Set parent parent for group {{ item }}
  freeipa.ansible_freeipa.ipagroup:
    ipaadmin_password: "{{ ipaadmin_pass }}"
    name: parent
    group: "{{ item }}"
  loop:
    - child1
    - child2
```

-------------------------------------
Run output for issue (1):
TASK [test : Create ipa group parent] ******************************************
changed: [infra01] => (item={'name': 'parent', 'gid': 9991})
changed: [infra01] => (item={'name': 'child1', 'gid': 9992})
changed: [infra01] => (item={'name': 'child2', 'gid': 9993})
Wednesday 27 July 2022  18:41:54 +0000 (0:00:09.433)       0:00:17.326 ******** 

TASK [test : Set parent parent for group child1] *******************************
changed: [infra01] => (item=child1)
changed: [infra01] => (item=child2)
Wednesday 27 July 2022  18:42:01 +0000 (0:00:06.584)       0:00:23.911 ******** 

TASK [test : Set parent parent for group child1] *******************************
changed: [infra01] => (item=child1)
changed: [infra01] => (item=child2)
Wednesday 27 July 2022  18:42:09 +0000 (0:00:08.187)       0:00:32.098 ******** 

Note that when I used one child, the second set parent reported OK.

------------------------
Run output for issue (2): the playbook is run with checkmode:

TASK [test : Create ipa group parent] ******************************************
ok: [infra01] => (item={'name': 'parent', 'gid': 9991})
ok: [infra01] => (item={'name': 'child1', 'gid': 9992})
ok: [infra01] => (item={'name': 'child2', 'gid': 9993})
Wednesday 27 July 2022  19:02:51 +0000 (0:00:09.925)       0:00:18.444 ******** 

TASK [test : Set parent parent for group child1] *******************************
changed: [infra01] => (item=child1)
ok: [infra01] => (item=child2)
Wednesday 27 July 2022  19:02:57 +0000 (0:00:06.272)       0:00:24.717 ******** 

TASK [test : Set parent parent for group child1] *******************************
changed: [infra01] => (item=child1)
ok: [infra01] => (item=child2)
Wednesday 27 July 2022  19:03:04 +0000 (0:00:06.967)       0:00:31.685 ******** 

Note that some set parent show changed, some show ok.
