### ISSUE TITLE
ipa-replica-install with no-ntp is ignored

### ISSUE THREAD

**Issue by frashman123** [freeipa/ansible-freeipa#871]
Hi,

the replica IPA installation with the no-ntp option fails. The option seems to be ignored. The IPA server and replicas are running in unprivileged Rocky 8 LXCs on a Proxmox cluster, so no ntp or chrony packages are installed. The server installation runs smoothly with the same options.

```
$ ansible-playbook -vv -i inventory.yml setup_ipa_replicas.yml
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home_ceph/$USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: setup_ipa_replicas.yml *************************************************************************************************************************************************************************************************************************************************
1 plays in setup_ipa_replicas.yml

PLAY [Playbook to configure IPA replicas] ****************************************************************************************************************************************************************************************************************************************

*** STRIP ***

TASK [ipaclient : Install - Configure NTP] ***************************************************************************************************************************************************************************************************************************************
task path: /home_ceph/$USER/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaclient/tasks/install.yml:61
fatal: [ipa2.example.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ipa2.example.com closed.
", "module_stdout": "Augeas failed to configure file /etc/chrony.conf
Using default chrony configuration.
Traceback (most recent call last):
  File \"/root/.ansible/tmp/ansible-tmp-1659943388.5090098-183431592480444/AnsiballZ_ipaclient_setup_ntp.py\", line 102, in <module>
    _ansiballz_main()
  File \"/root/.ansible/tmp/ansible-tmp-1659943388.5090098-183431592480444/AnsiballZ_ipaclient_setup_ntp.py\", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/root/.ansible/tmp/ansible-tmp-1659943388.5090098-183431592480444/AnsiballZ_ipaclient_setup_ntp.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.freeipa.ansible_freeipa.plugins.modules.ipaclient_setup_ntp', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_freeipa.ansible_freeipa.ipaclient_setup_ntp_payload_qwz3xzs_/ansible_freeipa.ansible_freeipa.ipaclient_setup_ntp_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipaclient_setup_ntp.py\", line 173, in <module>
  File \"/tmp/ansible_freeipa.ansible_freeipa.ipaclient_setup_ntp_payload_qwz3xzs_/ansible_freeipa.ansible_freeipa.ipaclient_setup_ntp_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipaclient_setup_ntp.py\", line 119, in main
  File \"/usr/lib/python3.6/site-packages/ipaclient/install/client.py\", line 2618, in sync_time
    return timeconf.sync_chrony()
  File \"/usr/lib/python3.6/site-packages/ipaclient/install/timeconf.py\", line 83, in sync_chrony
    services.knownservices.chronyd.restart()
  File \"/usr/lib/python3.6/site-packages/ipaplatform/base/services.py\", line 343, in restart
    capture_output, wait)
  File \"/usr/lib/python3.6/site-packages/ipaplatform/base/services.py\", line 329, in _restart_base
    skip_output=not capture_output)
  File \"/usr/lib/python3.6/site-packages/ipapython/ipautil.py\", line 599, in run
    p.returncode, arg_string, output_log, error_log
ipapython.ipautil.CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'restart', 'chronyd.service'] returned non-zero exit status 1: 'Job for chronyd.service failed because the control process exited with error code.\\nSee \"systemctl status chronyd.service\" and \"journalctl -xe\" for details.\\n')
", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

TASK [ipaclient : Install - Restore original admin password if overwritten by OTP] ***********************************************************************************************************************************************************************************************
task path: /home_ceph/$USER/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaclient/tasks/install.yml:375
skipping: [ipa2.example.com] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [ipaclient : Cleanup leftover ccache] ***************************************************************************************************************************************************************************************************************************************
task path: /home_ceph/$USER/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaclient/tasks/install.yml:381
ok: [ipa2.example.com] => {"changed": false, "path": "/etc/ipa/.dns_ccache", "state": "absent"}

TASK [ipareplica : Cleanup temporary files] **************************************************************************************************************************************************************************************************************************************
task path: /home_ceph/$USER/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipareplica/tasks/install.yml:786
ok: [ipa2.example.com] => (item=/etc/ipa/.tmp_pkcs12_dirsrv) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/ipa/.tmp_pkcs12_dirsrv", "path": "/etc/ipa/.tmp_pkcs12_dirsrv", "state": "absent"}
ok: [ipa2.example.com] => (item=/etc/ipa/.tmp_pkcs12_http) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/ipa/.tmp_pkcs12_http", "path": "/etc/ipa/.tmp_pkcs12_http", "state": "absent"}
ok: [ipa2.example.com] => (item=/etc/ipa/.tmp_pkcs12_pkinit) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/ipa/.tmp_pkcs12_pkinit", "path": "/etc/ipa/.tmp_pkcs12_pkinit", "state": "absent"}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************
ipa2.example.com               : ok=15   changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0   
```

the Playbook:

```
---
- name: Playbook to configure IPA replicas
  hosts: ipa_replicas
  remote_user: root
  vars_prompt:
    - name: ipaadmin_password
      prompt: Enter the IPA Admin Password
    - name: ipadm_password
      prompt: Enter the IPA Directory Manager Password

  roles:
  - role: ipareplica
    state: present
```
the Inventory:

```
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    ipa:
      children:
        ipa_server:
          vars:
            ipaadmin_password: "{{ ipaadmin_password }}"
            ipadm_password: "{{ ipadm_password }}"
            ipaserver_domain: example.com
            ipaserver_realm: EXAMPLE.COM
            ipaserver_setup_dns: no
            ipaclient_no_ntp: yes
            ipsaerver_setup_firewalld: yes
            ipaserver_setup_adtrust: yes
            ipaserver_idstart: 1120200000
            ipaserver_max: 1120209999
          hosts:
            ipa1.example.com:
        ipa_replicas:
          vars:
            ipaadmin_password: "{{ ipaadmin_password }}"
            ipadm_password: "{{ ipadm_password }}"
            ipaserver_domain: example.com
            ipaserver_realm: EXAMPLE.COM
            ipareplica_setup_dns: no
            ipaclient_no_ntp: yes
            ipareplica_setup_firewalld: yes
          hosts:
            ipa2.example.com:
```
