### ISSUE TITLE
ipauser chokes on update_password in batch creation

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#878]
The below playbook works if `operate_one_by_one` is set to `true` but fails when setting it to `false`. The error goes away when commenting out `update_password` from the user data. I can't see a reason why batch creation should not accept `update_password` as well.

```
---
- name: Configure IPA/IdM users
  hosts: ipaserver
  become: true
  vars_files:
    - vault_ipa.yml
  vars:
    ipa_users_create:
      - name: testuser
        first: first
        last: last
        uid: 12345
        update_password: on_create 
    operate_one_by_one: false
  tasks:
    - name: Create IPA/IdM user
      ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        first: "{{ item.first | default(omit) }}"
        last: "{{ item.last | default(omit) }}"
        uid: "{{ item.uid | default(omit) }}"
        update_password: "{{ item.update_password | default(omit) }}"
        state: present
      loop: "{{ ipa_users_create | select() | list }}"
      loop_control:
        label: "{{ item.name }}"
      when: operate_one_by_one | bool

    # Loop to display items
    - name: Create IPA/IdM users
      ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        users: "{{ item }}"
        state: present
      loop: "{{ [ipa_users_create] | select() | list }}"
      loop_control:
        index_var: i
        label: "{{ item[i].name }}"
      when: not operate_one_by_one | bool
```

FWIW, from the module I get the impression that `first`/`last` would not be required but in fact they are when creating a new user. I can file another ticket about that if it would be helpful. Thanks.
