### ISSUE TITLE
ipahost module prints warning

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#886]
Using this minimal test case:

```
---
- hosts: ipaserver
  become: true
  tasks:
    - name: Delete host
      ipahost:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: oldhost
        state: absent
```

Output contains:

```
TASK [Delete host] *************************************
[WARNING]: Module did not set no_log for update_password
ok: [idm1.sub.example.com]
```

This is with:

```
# rpm -qf $(which ansible-playbook)
ansible-core-2.12.2-4.el8_6.x86_64
```

Thanks.
